**Burbank 2018**
<br/>Create and cleans a dataframe of the 2018 Burbank airport adding origin and destination weather.
<br/>Run a comparison of the airlines and destinations in 2017 and 2018 and adjust dataframe accoridingly.

In [1]:
import numpy as np
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
# increase display size to enable viewing of all data columns

pd.options.display.max_columns = 40

In [4]:
# read in the clean flights csv

flights2018_df = pd.read_csv('flights2018clean.csv', index_col=0)
flights2018_df

,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Origin,OriginCityName,OriginState,Dest,DestCityName,DestState,CRSDepTime,DepTime,DepDelay,DepDel15,DepartureDelayGroups,TaxiOut,WheelsOff,Cancelled,CancellationCode,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,CRSArrTime,ArrTime,ArrDelay,Delayed
0,5,2018-08-31,UA,N75432,EWR,"Newark, NJ",NJ,DEN,"Denver, CO",CO,1601,1559.0,-2.0,0.0,-1.0,17.0,1616.0,0,0,1605,7,0.0,0.0,0.0,0.0,0.0,1818,1802.0,-16.0,0
1,5,2018-08-31,UA,N461UA,ORD,"Chicago, IL",IL,GEG,"Spokane, WA",WA,1932,1926.0,-6.0,0.0,-1.0,45.0,2011.0,0,0,1498,6,0.0,0.0,0.0,0.0,0.0,2128,2137.0,9.0,1
2,5,2018-08-31,UA,N76514,SNA,"Santa Ana, CA",CA,DEN,"Denver, CO",CO,1327,1636.0,189.0,1.0,12.0,20.0,1656.0,0,0,846,4,0.0,54.0,5.0,0.0,135.0,1642,1956.0,194.0,1
3,5,2018-08-31,UA,N76533,LAX,"Los Angeles, CA",CA,SFO,"San Francisco, CA",CA,600,550.0,-10.0,0.0,-1.0,16.0,606.0,0,0,337,2,0.0,0.0,0.0,0.0,0.0,730,710.0,-20.0,0
4,5,2018-08-31,UA,N35204,SFO,"San Francisco, CA",CA,SAN,"San Diego, CA",CA,2140,2141.0,1.0,1.0,0.0,31.0,2212.0,0,0,447,2,0.0,0.0,0.0,0.0,0.0,2311,2317.0,6.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7213441,4,2018-06-21,DL,N970AT,ORD,"Chicago, IL",IL,ATL,"Atlanta, GA",GA,1335,1354.0,19.0,1.0,1.0,33.0,1427.0,0,0,606,3,0.0,19.0,18.0,0.0,0.0,1640,1717.0,37.0,1
7213442,4,2018-06-21,DL,N927AT,BNA,"Nashville, TN",TN,MSP,"Minneapolis, MN",MN,1425,1417.0,-8.0,0.0,-1.0,14.0,1431.0,0,0,695,3,0.0,0.0,0.0,0.0,0.0,1642,1614.0,-28.0,0
7213443,4,2018-06-21,DL,N927AT,MSP,"Minneapolis, MN",MN,BNA,"Nashville, TN",TN,1125,1120.0,-5.0,0.0,-1.0,14.0,1134.0,0,0,695,3,0.0,0.0,0.0,0.0,0.0,1333,1317.0,-16.0,0
7213444,4,2018-06-21,DL,N320NB,AUS,"Austin, TX",TX,SLC,"Salt Lake City, UT",UT,1905,1931.0,26.0,1.0,1.0,9.0,1940.0,0,0,1086,5,0.0,0.0,0.0,0.0,0.0,2058,2111.0,13.0,1
7213445,4,2018-06-21,DL,N906AT,LGA,"New York, NY",NY,ORD,"Chicago, IL",IL,1915,2026.0,71.0,1.0,4.0,37.0,2103.0,0,0,733,3,0.0,0.0,63.0,0.0,0.0,2106,2209.0,63.0,1

In [5]:
# create a dataframe of the flights originating in Burbank

burbank2018_df = flights2018_df[(flights2018_df['Origin'] == 'BUR')]
burbank2018_df

,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Origin,OriginCityName,OriginState,Dest,DestCityName,DestState,CRSDepTime,DepTime,DepDelay,DepDel15,DepartureDelayGroups,TaxiOut,WheelsOff,Cancelled,CancellationCode,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,CRSArrTime,ArrTime,ArrDelay,Delayed
662,5,2018-08-31,UA,N899UA,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,2030,2014.0,-16.0,0.0,-2.0,18.0,2032.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,2200,2153.0,-7.0,0
980,5,2018-08-31,UA,N35204,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,700,721.0,21.0,1.0,1.0,13.0,734.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,826,834.0,8.0,1
1776,5,2018-08-31,UA,N810UA,BUR,"Burbank, CA",CA,DEN,"Denver, CO",CO,715,713.0,-2.0,0.0,-1.0,12.0,725.0,0,0,850,4,0.0,0.0,0.0,0.0,0.0,1035,1032.0,-3.0,0
2572,4,2018-08-30,UA,N833UA,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,2030,2024.0,-6.0,0.0,-1.0,16.0,2040.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,2200,2154.0,-6.0,0
2899,4,2018-08-30,UA,N76505,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,700,657.0,-3.0,0.0,-1.0,22.0,719.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,826,823.0,-3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7123869,2,2018-06-19,UA,N26226,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,1956,2202.0,126.0,1.0,8.0,13.0,2215.0,0,0,326,2,0.0,0.0,0.0,0.0,118.0,2115,2313.0,118.0,1
7124727,2,2018-06-19,UA,N26215,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,700,658.0,-2.0,0.0,-1.0,19.0,717.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,835,815.0,-20.0,0
7125797,1,2018-06-18,UA,N77536,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,1956,2003.0,7.0,1.0,0.0,11.0,2014.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,2115,2110.0,-5.0,0
7126660,1,2018-06-18,UA,N35271,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,700,718.0,18.0,1.0,1.0,39.0,757.0,0,0,326,2,0.0,0.0,23.0,0.0,0.0,835,858.0,23.0,1
7127679,7,2018-06-17,UA,N77258,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,1956,1956.0,0.0,0.0,0.0,14.0,2010.0,0,0,326,2,0.0,0.0,30.0,0.0,0.0,2115,2145.0,30.0,1

In [6]:
# read in the burbank 2017 file to be used to compare data points

burbank2017_df = pd.read_csv('burbank2017comp.csv')
burbank2017_df.drop(['Unnamed: 0'], axis=1, inplace=True)
burbank2017_df

,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Origin,OriginCityName,OriginState,Dest,DestCityName,DestState,CRSDepTime,DepTime,DepDelay,DepDel15,DepartureDelayGroups,TaxiOut,WheelsOff,Cancelled,CancellationCode,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,CRSArrTime,ArrTime,ArrDelay,Delayed
0,6,2017-07-01,AS,N520AS,BUR,"Burbank, CA",CA,SEA,"Seattle, WA",WA,700,708.0,8.0,0.0,0.0,13.0,721.0,0,0,937,4,0.0,0.0,0.0,0.0,0.0,930,942.0,12.0,1
1,6,2017-07-01,AS,N563AS,BUR,"Burbank, CA",CA,SEA,"Seattle, WA",WA,1730,1720.0,-10.0,0.0,-1.0,22.0,1742.0,0,0,937,4,0.0,0.0,0.0,0.0,0.0,1958,2010.0,12.0,1
2,6,2017-07-01,AS,N562AS,BUR,"Burbank, CA",CA,SEA,"Seattle, WA",WA,1215,1212.0,-3.0,0.0,-1.0,22.0,1234.0,0,0,937,4,0.0,0.0,16.0,0.0,0.0,1443,1459.0,16.0,1
3,7,2017-07-02,AS,N530AS,BUR,"Burbank, CA",CA,SEA,"Seattle, WA",WA,700,657.0,-3.0,0.0,-1.0,14.0,711.0,0,0,937,4,0.0,0.0,0.0,0.0,0.0,930,941.0,11.0,1
4,7,2017-07-02,AS,N527AS,BUR,"Burbank, CA",CA,SEA,"Seattle, WA",WA,1730,1721.0,-9.0,0.0,-1.0,13.0,1734.0,0,0,937,4,0.0,0.0,0.0,0.0,0.0,1958,1947.0,-11.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25100,2,2017-09-19,UA,N36207,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,708,706.0,-2.0,0.0,-1.0,32.0,738.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,833,841.0,8.0,1
25101,2,2017-09-19,UA,N836UA,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,2015,2000.0,-15.0,0.0,-1.0,18.0,2018.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,2141,2125.0,-16.0,0
25102,2,2017-09-19,UA,N14240,BUR,"Burbank, CA",CA,DEN,"Denver, CO",CO,700,651.0,-9.0,0.0,-1.0,26.0,717.0,0,0,850,4,0.0,0.0,0.0,0.0,0.0,1029,1012.0,-17.0,0
25103,2,2017-09-05,UA,N78285,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,1220,1214.0,-6.0,0.0,-1.0,10.0,1224.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,1339,1319.0,-20.0,0
25104,2,2017-09-05,UA,N73276,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,715,722.0,7.0,0.0,0.0,15.0,737.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,847,850.0,3.0,1

In [7]:
# check to see whether 2017 and 2018 have the same number of unique destinations

print('2017: ' + str(burbank2017_df['Dest'].nunique()))
print('2018: ' + str(burbank2018_df['Dest'].nunique()))
print('Difference: ' + str(burbank2018_df['Dest'].nunique() - burbank2017_df['Dest'].nunique()))

2017: 12
2018: 15
Difference: 3

In [8]:
# create a new dataframe with the 2017 and 2018 destinations

comparison_df = pd.DataFrame()
comparison_df['Dest18'] = burbank2018_df['Dest']
comparison_df.reset_index(drop=True, inplace=True)
comparison_df['Dest17'] = burbank2017_df['Dest']
comparison_df

      Dest18 Dest17
0        SFO    SEA
1        SFO    SEA
2        DEN    SEA
3        SFO    SEA
4        SFO    SEA
...      ...    ...
26574    SFO    NaN
26575    SFO    NaN
26576    SFO    NaN
26577    SFO    NaN
26578    SFO    NaN

[26579 rows x 2 columns]

In [9]:
# check to see which destinations exist in 2017, but not 2018

comparison_df['Unique'] = comparison_df['Dest17'][~comparison_df['Dest17'].isin(comparison_df['Dest18'])].drop_duplicates()
display(comparison_df['Unique'].nunique())

difference_df = pd.DataFrame()
difference_df = comparison_df['Unique'].value_counts()
difference = difference_df.index.to_list()
difference

0

[]

In [10]:
# check to see which destinations exist in 2018, but not 2017

comparison_df['Unique'] = comparison_df['Dest18'][~comparison_df['Dest18'].isin(comparison_df['Dest17'])].drop_duplicates()
display(comparison_df['Unique'].nunique())

difference_df = pd.DataFrame(columns=['Destination', 'Occurence'])
difference_df = comparison_df['Unique'].value_counts()
difference = difference_df.index.to_list()
difference

3

['BOS', 'HOU', 'MDW']

In [11]:
# drop any rows pertaining to HOU, MDW or BOS

burbank2018_df = burbank2018_df.drop(burbank2018_df[(burbank2018_df['Dest'] == 'BOS')].index)
burbank2018_df = burbank2018_df.drop(burbank2018_df[(burbank2018_df['Dest'] == 'MDW')].index)
burbank2018_df = burbank2018_df.drop(burbank2018_df[(burbank2018_df['Dest'] == 'HOU')].index)
burbank2018_df['Dest'].value_counts()

OAK    4202
SJC    3543
SFO    3404
LAS    3327
PHX    3238
SMF    2833
DEN    1570
SLC    1218
SEA    1216
PDX    1004
JFK     447
DAL     360
Name: Dest, dtype: int64

In [12]:
# check to see whether 2017 and 2018 have the same number of unique reporting airlines

print('2017: ' + str(burbank2017_df['Reporting_Airline'].nunique()))
print('2018: ' + str(burbank2018_df['Reporting_Airline'].nunique()))
print('Difference: ' + str(burbank2018_df['Reporting_Airline'].nunique() - burbank2017_df['Reporting_Airline'].nunique()))

2017: 5
2018: 6
Difference: 1

In [13]:
# create a new dataframe with the 2017 and 2018 reporting airlines

comparison_df = pd.DataFrame()
comparison_df['Airline18'] = burbank2018_df['Reporting_Airline']
comparison_df.reset_index(drop=True, inplace=True)
comparison_df['Airline17'] = burbank2017_df['Reporting_Airline']
comparison_df

      Airline18 Airline17
0            UA        AS
1            UA        AS
2            UA        AS
3            UA        AS
4            UA        AS
...         ...       ...
26357        UA       NaN
26358        UA       NaN
26359        UA       NaN
26360        UA       NaN
26361        UA       NaN

[26362 rows x 2 columns]

In [14]:
# check to see which reporting airlines exist in 2017, but not 2018

comparison_df['Unique'] = comparison_df['Airline17'][~comparison_df['Airline17'].isin(comparison_df['Airline18'])].drop_duplicates()
display(comparison_df['Unique'].nunique())

difference_df = pd.DataFrame()
difference_df = comparison_df['Unique'].value_counts()
difference = difference_df.index.to_list()
difference

0

[]

In [15]:
# check to see which destinations exist in 2018, but not 2017

comparison_df['Unique'] = comparison_df['Airline18'][~comparison_df['Airline18'].isin(comparison_df['Airline17'])].drop_duplicates()
display(comparison_df['Unique'].nunique())

difference_df = pd.DataFrame(columns=['Destination', 'Occurence'])
difference_df = comparison_df['Unique'].value_counts()
difference = difference_df.index.to_list()
difference

1

['YV']

In [16]:
# drop any rows pertaining to HOU, MDW or BOSburbank2018_df = burbank2018_df.drop(burbank2018_df[(burbank2018_df['Reporting_Airline'] == 'YV')].index)

burbank2018_df = burbank2018_df.drop(burbank2018_df[(burbank2018_df['Reporting_Airline'] == 'YV')].index)
burbank2018_df['Reporting_Airline'].value_counts()

WN    18809
OO     3617
AS     1673
UA      681
B6      447
Name: Reporting_Airline, dtype: int64

In [17]:
# review the dataframe

burbank2018_df

,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Origin,OriginCityName,OriginState,Dest,DestCityName,DestState,CRSDepTime,DepTime,DepDelay,DepDel15,DepartureDelayGroups,TaxiOut,WheelsOff,Cancelled,CancellationCode,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,CRSArrTime,ArrTime,ArrDelay,Delayed
662,5,2018-08-31,UA,N899UA,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,2030,2014.0,-16.0,0.0,-2.0,18.0,2032.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,2200,2153.0,-7.0,0
980,5,2018-08-31,UA,N35204,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,700,721.0,21.0,1.0,1.0,13.0,734.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,826,834.0,8.0,1
1776,5,2018-08-31,UA,N810UA,BUR,"Burbank, CA",CA,DEN,"Denver, CO",CO,715,713.0,-2.0,0.0,-1.0,12.0,725.0,0,0,850,4,0.0,0.0,0.0,0.0,0.0,1035,1032.0,-3.0,0
2572,4,2018-08-30,UA,N833UA,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,2030,2024.0,-6.0,0.0,-1.0,16.0,2040.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,2200,2154.0,-6.0,0
2899,4,2018-08-30,UA,N76505,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,700,657.0,-3.0,0.0,-1.0,22.0,719.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,826,823.0,-3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7123869,2,2018-06-19,UA,N26226,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,1956,2202.0,126.0,1.0,8.0,13.0,2215.0,0,0,326,2,0.0,0.0,0.0,0.0,118.0,2115,2313.0,118.0,1
7124727,2,2018-06-19,UA,N26215,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,700,658.0,-2.0,0.0,-1.0,19.0,717.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,835,815.0,-20.0,0
7125797,1,2018-06-18,UA,N77536,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,1956,2003.0,7.0,1.0,0.0,11.0,2014.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,2115,2110.0,-5.0,0
7126660,1,2018-06-18,UA,N35271,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,700,718.0,18.0,1.0,1.0,39.0,757.0,0,0,326,2,0.0,0.0,23.0,0.0,0.0,835,858.0,23.0,1
7127679,7,2018-06-17,UA,N77258,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,1956,1956.0,0.0,0.0,0.0,14.0,2010.0,0,0,326,2,0.0,0.0,30.0,0.0,0.0,2115,2145.0,30.0,1

In [18]:
burbank2018_df.to_csv('burbank2018comp.csv')

In [19]:
# drop columns with redundant, 'give-away', or unuseful information

burbank2018_df.drop(['Tail_Number', 
                     'OriginCityName', 
                     'DestCityName',
                     'DepTime', 
                     'DepDel15', 
                     'DepartureDelayGroups', 
                     'TaxiOut', 
                     'WheelsOff',
                     'DistanceGroup',
                     'CarrierDelay',
                     'WeatherDelay',
                     'NASDelay',
                     'SecurityDelay',
                     'LateAircraftDelay',
                     'CancellationCode'], inplace=True, axis=1)
burbank2018_df

,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed
662,5,2018-08-31,UA,BUR,CA,SFO,CA,2030,-16.0,0,326,2200,2153.0,-7.0,0
980,5,2018-08-31,UA,BUR,CA,SFO,CA,700,21.0,0,326,826,834.0,8.0,1
1776,5,2018-08-31,UA,BUR,CA,DEN,CO,715,-2.0,0,850,1035,1032.0,-3.0,0
2572,4,2018-08-30,UA,BUR,CA,SFO,CA,2030,-6.0,0,326,2200,2154.0,-6.0,0
2899,4,2018-08-30,UA,BUR,CA,SFO,CA,700,-3.0,0,326,826,823.0,-3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7123869,2,2018-06-19,UA,BUR,CA,SFO,CA,1956,126.0,0,326,2115,2313.0,118.0,1
7124727,2,2018-06-19,UA,BUR,CA,SFO,CA,700,-2.0,0,326,835,815.0,-20.0,0
7125797,1,2018-06-18,UA,BUR,CA,SFO,CA,1956,7.0,0,326,2115,2110.0,-5.0,0
7126660,1,2018-06-18,UA,BUR,CA,SFO,CA,700,18.0,0,326,835,858.0,23.0,1
7127679,7,2018-06-17,UA,BUR,CA,SFO,CA,1956,0.0,0,326,2115,2145.0,30.0,1

In [20]:
# summary statistics for the dataframe

burbank2018_df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
DayOfWeek,25227.0,3.845919,1.974588,1.0,2.0,4.0,5.0,7.0
CRSDepTime,25227.0,1353.855789,452.679903,700.0,940.0,1330.0,1745.0,2159.0
DepDelay,25227.0,9.471915,37.776344,-28.0,-4.0,-1.0,9.0,1420.0
Cancelled,25227.0,0.016966,0.129146,0.0,0.0,0.0,0.0,1.0
Distance,25227.0,459.779244,353.016591,223.0,296.0,326.0,369.0,2465.0
CRSArrTime,25227.0,1495.871725,452.105913,513.0,1105.0,1510.0,1920.0,2355.0
ArrTime,25227.0,1470.421651,502.208762,0.0,1052.0,1458.0,1917.0,2400.0
ArrDelay,25227.0,5.494074,49.956637,-2212.0,-10.0,-3.0,8.0,1432.0
Delayed,25227.0,0.376145,0.484427,0.0,0.0,0.0,1.0,1.0

In [21]:
# import all the weather data

weather_df = pd.read_csv('data/weather/all13_weather.csv')
weather_df

,STATION,NAME,AIRPORT,DATE,AWND,PGTM,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,TOBS,WDF2,WDF5,WSF2,WSF5
0,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2017-01-01,9.62,NaN,0.43,3.0,2.0,35.0,37.0,28.0,NaN,10.0,10.0,16.1,19.0
1,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2017-01-02,10.51,NaN,0.00,0.0,2.0,32.0,34.0,26.0,NaN,70.0,60.0,15.0,19.0
2,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2017-01-03,11.86,NaN,0.00,0.0,2.0,27.0,33.0,21.0,NaN,20.0,20.0,18.1,21.9
3,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2017-01-04,10.96,NaN,0.00,0.0,1.2,27.0,36.0,22.0,NaN,20.0,20.0,16.1,19.0
4,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2017-01-05,5.82,NaN,0.00,0.0,0.0,28.0,35.0,21.0,NaN,40.0,40.0,15.0,16.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14230,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-27,11.41,838.0,0.00,NaN,NaN,NaN,53.0,34.0,NaN,290.0,280.0,23.0,28.0
14231,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-28,6.04,8.0,0.00,NaN,NaN,NaN,40.0,30.0,NaN,100.0,290.0,12.1,15.0
14232,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-29,8.28,1055.0,0.87,NaN,NaN,NaN,44.0,36.0,NaN,110.0,100.0,19.9,27.1
14233,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-30,16.11,1238.0,0.44,NaN,NaN,NaN,44.0,31.0,NaN,220.0,220.0,29.1,44.1
14234,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-31,13.65,659.0,0.00,NaN,NaN,NaN,32.0,27.0,NaN,240.0,250.0,25.9,38.0

In [22]:
# create a dataframe of the 2018 weather

weather2018_df = weather_df[(pd.DatetimeIndex(weather_df['DATE']).year == 2018)]
weather2018_df

,STATION,NAME,AIRPORT,DATE,AWND,PGTM,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,TOBS,WDF2,WDF5,WSF2,WSF5
365,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2018-01-01,8.72,NaN,0.00,0.0,0.0,36.0,44.0,31.0,NaN,20.0,20.0,15.0,17.0
366,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2018-01-02,7.83,NaN,0.00,0.0,0.0,37.0,44.0,34.0,NaN,30.0,20.0,15.0,18.1
367,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2018-01-03,8.72,NaN,0.00,0.0,0.0,39.0,49.0,33.0,NaN,20.0,30.0,13.0,17.0
368,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2018-01-04,2.68,NaN,0.13,0.0,0.0,41.0,47.0,35.0,NaN,120.0,90.0,10.1,12.1
369,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2018-01-05,6.49,NaN,0.51,0.0,0.0,46.0,51.0,45.0,NaN,110.0,110.0,19.9,23.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13865,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2018-12-27,13.87,1947.0,0.17,NaN,NaN,NaN,45.0,32.0,NaN,120.0,150.0,23.0,33.1
13866,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2018-12-28,13.87,1449.0,0.00,NaN,NaN,NaN,54.0,33.0,NaN,270.0,230.0,30.0,38.0
13867,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2018-12-29,6.49,8.0,0.00,NaN,NaN,NaN,34.0,27.0,NaN,320.0,230.0,16.1,21.9
13868,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2018-12-30,8.50,457.0,0.00,NaN,NaN,NaN,33.0,26.0,NaN,240.0,230.0,17.0,21.0
13869,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2018-12-31,6.93,2250.0,0.85,NaN,NaN,NaN,40.0,28.0,NaN,300.0,290.0,18.1,23.0

In [23]:
# look at the total number of NaN values for each column

weather2018_df.isna().sum()

STATION       0
NAME          0
AIRPORT       0
DATE          0
AWND          0
PGTM       4141
PRCP          2
SNOW       1147
SNWD       1131
TAVG       1460
TMAX         29
TMIN         29
TOBS       4380
WDF2        730
WDF5        739
WSF2        730
WSF5        739
dtype: int64

In [24]:
# TMAX and TMIN will be used to generate missing values for TAVG and are only missing a few values -- fill using forward fill

weather2018_df['TMAX'].ffill(inplace=True)
weather2018_df['TMIN'].ffill(inplace=True)
weather2018_df.isna().sum()

STATION       0
NAME          0
AIRPORT       0
DATE          0
AWND          0
PGTM       4141
PRCP          2
SNOW       1147
SNWD       1131
TAVG       1460
TMAX          0
TMIN          0
TOBS       4380
WDF2        730
WDF5        739
WSF2        730
WSF5        739
dtype: int64

In [25]:
# create a temporary column calculating the average temperature using TMAX and TMIN

weather2018_df['temp_avg'] = (weather2018_df['TMAX'] + weather2018_df['TMIN']) / 2
weather2018_df

,STATION,NAME,AIRPORT,DATE,AWND,PGTM,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,TOBS,WDF2,WDF5,WSF2,WSF5,temp_avg
365,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2018-01-01,8.72,NaN,0.00,0.0,0.0,36.0,44.0,31.0,NaN,20.0,20.0,15.0,17.0,37.5
366,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2018-01-02,7.83,NaN,0.00,0.0,0.0,37.0,44.0,34.0,NaN,30.0,20.0,15.0,18.1,39.0
367,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2018-01-03,8.72,NaN,0.00,0.0,0.0,39.0,49.0,33.0,NaN,20.0,30.0,13.0,17.0,41.0
368,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2018-01-04,2.68,NaN,0.13,0.0,0.0,41.0,47.0,35.0,NaN,120.0,90.0,10.1,12.1,41.0
369,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2018-01-05,6.49,NaN,0.51,0.0,0.0,46.0,51.0,45.0,NaN,110.0,110.0,19.9,23.9,48.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13865,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2018-12-27,13.87,1947.0,0.17,NaN,NaN,NaN,45.0,32.0,NaN,120.0,150.0,23.0,33.1,38.5
13866,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2018-12-28,13.87,1449.0,0.00,NaN,NaN,NaN,54.0,33.0,NaN,270.0,230.0,30.0,38.0,43.5
13867,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2018-12-29,6.49,8.0,0.00,NaN,NaN,NaN,34.0,27.0,NaN,320.0,230.0,16.1,21.9,30.5
13868,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2018-12-30,8.50,457.0,0.00,NaN,NaN,NaN,33.0,26.0,NaN,240.0,230.0,17.0,21.0,29.5
13869,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2018-12-31,6.93,2250.0,0.85,NaN,NaN,NaN,40.0,28.0,NaN,300.0,290.0,18.1,23.0,34.0

In [26]:
# fill in the missing TAVG values using the newly created average temperature column

weather2018_df['TAVG'].fillna(weather2018_df['temp_avg'], inplace=True)
weather2018_df.isna().sum()

STATION        0
NAME           0
AIRPORT        0
DATE           0
AWND           0
PGTM        4141
PRCP           2
SNOW        1147
SNWD        1131
TAVG           0
TMAX           0
TMIN           0
TOBS        4380
WDF2         730
WDF5         739
WSF2         730
WSF5         739
temp_avg       0
dtype: int64

In [27]:
# drop unnecessary and/or redundant columns

weather2018_df.drop(['STATION', 
                     'NAME', 
                     'PGTM', 
                     'SNWD', 
                     'TMAX', 
                     'TMIN', 
                     'TOBS', 
                     'WDF2', 
                     'WDF5', 
                     'WSF2', 
                     'WSF5',
                     'temp_avg'], axis=1, inplace=True)
weather2018_df

      AIRPORT        DATE   AWND  PRCP  SNOW  TAVG
365       SEA  2018-01-01   8.72  0.00   0.0  36.0
366       SEA  2018-01-02   7.83  0.00   0.0  37.0
367       SEA  2018-01-03   8.72  0.00   0.0  39.0
368       SEA  2018-01-04   2.68  0.13   0.0  41.0
369       SEA  2018-01-05   6.49  0.51   0.0  46.0
...       ...         ...    ...   ...   ...   ...
13865     OAK  2018-12-27  13.87  0.17   NaN  38.5
13866     OAK  2018-12-28  13.87  0.00   NaN  43.5
13867     OAK  2018-12-29   6.49  0.00   NaN  30.5
13868     OAK  2018-12-30   8.50  0.00   NaN  29.5
13869     OAK  2018-12-31   6.93  0.85   NaN  34.0

[4745 rows x 6 columns]

In [28]:
# check for any remaining NaN values

weather2018_df.isna().sum()

AIRPORT       0
DATE          0
AWND          0
PRCP          2
SNOW       1147
TAVG          0
dtype: int64

In [29]:
# investigate which airports are missing values for SNOW

weather2018_df['AIRPORT'][(weather2018_df['SNOW'].isna())].value_counts()

SJC    365
OAK    365
BUR    365
PHX     31
SFO     21
Name: AIRPORT, dtype: int64

In [30]:
# all airports in warm climates where snow is unlikely... so input zeros for the NaNs

weather2018_df['SNOW'].fillna(0, inplace=True)
weather2018_df.isna().sum()

AIRPORT    0
DATE       0
AWND       0
PRCP       2
SNOW       0
TAVG       0
dtype: int64

In [31]:
# investigate the row missing precipitation information

weather2018_df[(weather2018_df['PRCP'].isna())]

      AIRPORT        DATE  AWND  PRCP  SNOW  TAVG
5071      SMF  2018-11-23  5.90   NaN   0.0  57.5
13799     OAK  2018-10-22  4.92   NaN   0.0  45.0

In [32]:
# fill in these missing values using forward fill

weather2018_df['PRCP'].ffill(inplace=True)
weather2018_df.isna().sum()

AIRPORT    0
DATE       0
AWND       0
PRCP       0
SNOW       0
TAVG       0
dtype: int64

In [33]:
# rename the columns with more intuitive names

weather2018_df.columns = ['AIRPORT', 
                          'DATE', 
                          'WIND', 
                          'PRCP', 
                          'SNOW', 
                          'TEMP']
weather2018_df

      AIRPORT        DATE   WIND  PRCP  SNOW  TEMP
365       SEA  2018-01-01   8.72  0.00   0.0  36.0
366       SEA  2018-01-02   7.83  0.00   0.0  37.0
367       SEA  2018-01-03   8.72  0.00   0.0  39.0
368       SEA  2018-01-04   2.68  0.13   0.0  41.0
369       SEA  2018-01-05   6.49  0.51   0.0  46.0
...       ...         ...    ...   ...   ...   ...
13865     OAK  2018-12-27  13.87  0.17   0.0  38.5
13866     OAK  2018-12-28  13.87  0.00   0.0  43.5
13867     OAK  2018-12-29   6.49  0.00   0.0  30.5
13868     OAK  2018-12-30   8.50  0.00   0.0  29.5
13869     OAK  2018-12-31   6.93  0.85   0.0  34.0

[4745 rows x 6 columns]

In [34]:
# ensure that the date column in both datafranes is of type datetime

pd.to_datetime(burbank2018_df['FlightDate'])
pd.to_datetime(weather2018_df['DATE'])

365     2018-01-01
366     2018-01-02
367     2018-01-03
368     2018-01-04
369     2018-01-05
           ...
13865   2018-12-27
13866   2018-12-28
13867   2018-12-29
13868   2018-12-30
13869   2018-12-31
Name: DATE, Length: 4745, dtype: datetime64[ns]

In [35]:
# ensure there is an entire year of data

display(burbank2018_df['FlightDate'].min())
display(burbank2018_df['FlightDate'].max())

'2018-01-01'

'2018-12-31'

In [36]:
# add in the origin airport weather to the burbank dataframe

burbank2018_df = pd.merge(burbank2018_df, weather2018_df, left_on=['FlightDate', 'Origin'], right_on=['DATE', 'AIRPORT'], how='left')
burbank2018_df.drop(columns=['AIRPORT', 'DATE'], axis=1, inplace=True)
burbank2018_df

,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,WIND,PRCP,SNOW,TEMP
0,5,2018-08-31,UA,BUR,CA,SFO,CA,2030,-16.0,0,326,2200,2153.0,-7.0,0,6.93,0.0,0.0,74.0
1,5,2018-08-31,UA,BUR,CA,SFO,CA,700,21.0,0,326,826,834.0,8.0,1,6.93,0.0,0.0,74.0
2,5,2018-08-31,UA,BUR,CA,DEN,CO,715,-2.0,0,850,1035,1032.0,-3.0,0,6.93,0.0,0.0,74.0
3,4,2018-08-30,UA,BUR,CA,SFO,CA,2030,-6.0,0,326,2200,2154.0,-6.0,0,7.38,0.0,0.0,75.5
4,4,2018-08-30,UA,BUR,CA,SFO,CA,700,-3.0,0,326,826,823.0,-3.0,0,7.38,0.0,0.0,75.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25222,2,2018-06-19,UA,BUR,CA,SFO,CA,1956,126.0,0,326,2115,2313.0,118.0,1,8.05,0.0,0.0,68.5
25223,2,2018-06-19,UA,BUR,CA,SFO,CA,700,-2.0,0,326,835,815.0,-20.0,0,8.05,0.0,0.0,68.5
25224,1,2018-06-18,UA,BUR,CA,SFO,CA,1956,7.0,0,326,2115,2110.0,-5.0,0,11.18,0.0,0.0,65.0
25225,1,2018-06-18,UA,BUR,CA,SFO,CA,700,18.0,0,326,835,858.0,23.0,1,11.18,0.0,0.0,65.0
25226,7,2018-06-17,UA,BUR,CA,SFO,CA,1956,0.0,0,326,2115,2145.0,30.0,1,8.95,0.0,0.0,62.5

In [37]:
# ensure the start and end dates are still correct

display(burbank2018_df['FlightDate'].min())
display(burbank2018_df['FlightDate'].max())

'2018-01-01'

'2018-12-31'

In [38]:
# check that the new columns have the correct values for Jan 1, 2018

burbank2018_df[(burbank2018_df['FlightDate'] == '2018-01-01')].head()

,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,WIND,PRCP,SNOW,TEMP
8355,1,2018-01-01,AS,BUR,CA,SEA,WA,700,-7.0,0,937,943,936.0,-7.0,0,4.03,0.0,0.0,59.5
8356,1,2018-01-01,AS,BUR,CA,PDX,OR,1840,-10.0,0,817,2100,2039.0,-21.0,0,4.03,0.0,0.0,59.5
8357,1,2018-01-01,AS,BUR,CA,PDX,OR,1050,-4.0,0,817,1310,1304.0,-6.0,0,4.03,0.0,0.0,59.5
8358,1,2018-01-01,AS,BUR,CA,SEA,WA,1711,-16.0,0,937,1957,1930.0,-27.0,0,4.03,0.0,0.0,59.5
8359,1,2018-01-01,AS,BUR,CA,SEA,WA,1212,84.0,0,937,1445,1619.0,94.0,1,4.03,0.0,0.0,59.5

In [39]:
# rename the new weather columns so that we know they pertain to the origin airport

burbank2018_df.rename(columns={'WIND' : 'Origin_WIND',
                                'PRCP' : 'Origin_PRCP',
                                'SNOW' : 'Origin_SNOW',
                                'TEMP' : 'Origin_TEMP'}, inplace=True)
burbank2018_df.head()

,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP
0,5,2018-08-31,UA,BUR,CA,SFO,CA,2030,-16.0,0,326,2200,2153.0,-7.0,0,6.93,0.0,0.0,74.0
1,5,2018-08-31,UA,BUR,CA,SFO,CA,700,21.0,0,326,826,834.0,8.0,1,6.93,0.0,0.0,74.0
2,5,2018-08-31,UA,BUR,CA,DEN,CO,715,-2.0,0,850,1035,1032.0,-3.0,0,6.93,0.0,0.0,74.0
3,4,2018-08-30,UA,BUR,CA,SFO,CA,2030,-6.0,0,326,2200,2154.0,-6.0,0,7.38,0.0,0.0,75.5
4,4,2018-08-30,UA,BUR,CA,SFO,CA,700,-3.0,0,326,826,823.0,-3.0,0,7.38,0.0,0.0,75.5

In [40]:
# add in the destination airport weather

burbank2018_df = pd.merge(burbank2018_df, weather2018_df, left_on=['FlightDate', 'Dest'], right_on=['DATE', 'AIRPORT'], how='left')
burbank2018_df.drop(columns=['AIRPORT', 'DATE'], axis=1, inplace=True)
burbank2018_df

,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP,WIND,PRCP,SNOW,TEMP
0,5,2018-08-31,UA,BUR,CA,SFO,CA,2030,-16.0,0,326,2200,2153.0,-7.0,0,6.93,0.0,0.0,74.0,15.21,0.0,0.0,62.0
1,5,2018-08-31,UA,BUR,CA,SFO,CA,700,21.0,0,326,826,834.0,8.0,1,6.93,0.0,0.0,74.0,15.21,0.0,0.0,62.0
2,5,2018-08-31,UA,BUR,CA,DEN,CO,715,-2.0,0,850,1035,1032.0,-3.0,0,6.93,0.0,0.0,74.0,9.40,0.0,0.0,76.0
3,4,2018-08-30,UA,BUR,CA,SFO,CA,2030,-6.0,0,326,2200,2154.0,-6.0,0,7.38,0.0,0.0,75.5,11.18,0.0,0.0,65.0
4,4,2018-08-30,UA,BUR,CA,SFO,CA,700,-3.0,0,326,826,823.0,-3.0,0,7.38,0.0,0.0,75.5,11.18,0.0,0.0,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25222,2,2018-06-19,UA,BUR,CA,SFO,CA,1956,126.0,0,326,2115,2313.0,118.0,1,8.05,0.0,0.0,68.5,14.09,0.0,0.0,60.0
25223,2,2018-06-19,UA,BUR,CA,SFO,CA,700,-2.0,0,326,835,815.0,-20.0,0,8.05,0.0,0.0,68.5,14.09,0.0,0.0,60.0
25224,1,2018-06-18,UA,BUR,CA,SFO,CA,1956,7.0,0,326,2115,2110.0,-5.0,0,11.18,0.0,0.0,65.0,12.75,0.0,0.0,65.0
25225,1,2018-06-18,UA,BUR,CA,SFO,CA,700,18.0,0,326,835,858.0,23.0,1,11.18,0.0,0.0,65.0,12.75,0.0,0.0,65.0
25226,7,2018-06-17,UA,BUR,CA,SFO,CA,1956,0.0,0,326,2115,2145.0,30.0,1,8.95,0.0,0.0,62.5,8.72,0.0,0.0,62.0

In [41]:
# rename the new weather columns so that we know they pertain to the destination airport

burbank2018_df.rename(columns={'WIND' : 'Dest_WIND',
                               'PRCP' : 'Dest_PRCP',
                               'SNOW' : 'Dest_SNOW',
                               'TEMP' : 'Dest_TEMP'}, inplace=True)                               
burbank2018_df

,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP,Dest_WIND,Dest_PRCP,Dest_SNOW,Dest_TEMP
0,5,2018-08-31,UA,BUR,CA,SFO,CA,2030,-16.0,0,326,2200,2153.0,-7.0,0,6.93,0.0,0.0,74.0,15.21,0.0,0.0,62.0
1,5,2018-08-31,UA,BUR,CA,SFO,CA,700,21.0,0,326,826,834.0,8.0,1,6.93,0.0,0.0,74.0,15.21,0.0,0.0,62.0
2,5,2018-08-31,UA,BUR,CA,DEN,CO,715,-2.0,0,850,1035,1032.0,-3.0,0,6.93,0.0,0.0,74.0,9.40,0.0,0.0,76.0
3,4,2018-08-30,UA,BUR,CA,SFO,CA,2030,-6.0,0,326,2200,2154.0,-6.0,0,7.38,0.0,0.0,75.5,11.18,0.0,0.0,65.0
4,4,2018-08-30,UA,BUR,CA,SFO,CA,700,-3.0,0,326,826,823.0,-3.0,0,7.38,0.0,0.0,75.5,11.18,0.0,0.0,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25222,2,2018-06-19,UA,BUR,CA,SFO,CA,1956,126.0,0,326,2115,2313.0,118.0,1,8.05,0.0,0.0,68.5,14.09,0.0,0.0,60.0
25223,2,2018-06-19,UA,BUR,CA,SFO,CA,700,-2.0,0,326,835,815.0,-20.0,0,8.05,0.0,0.0,68.5,14.09,0.0,0.0,60.0
25224,1,2018-06-18,UA,BUR,CA,SFO,CA,1956,7.0,0,326,2115,2110.0,-5.0,0,11.18,0.0,0.0,65.0,12.75,0.0,0.0,65.0
25225,1,2018-06-18,UA,BUR,CA,SFO,CA,700,18.0,0,326,835,858.0,23.0,1,11.18,0.0,0.0,65.0,12.75,0.0,0.0,65.0
25226,7,2018-06-17,UA,BUR,CA,SFO,CA,1956,0.0,0,326,2115,2145.0,30.0,1,8.95,0.0,0.0,62.5,8.72,0.0,0.0,62.0

In [42]:
# ensure there are no NaN values in the burbank dataframe

burbank2018_df.isna().sum()

DayOfWeek            0
FlightDate           0
Reporting_Airline    0
Origin               0
OriginState          0
Dest                 0
DestState            0
CRSDepTime           0
DepDelay             0
Cancelled            0
Distance             0
CRSArrTime           0
ArrTime              0
ArrDelay             0
Delayed              0
Origin_WIND          0
Origin_PRCP          0
Origin_SNOW          0
Origin_TEMP          0
Dest_WIND            0
Dest_PRCP            0
Dest_SNOW            0
Dest_TEMP            0
dtype: int64

In [43]:
# set the Date to be a datecolumn and extract each of day, month and year separately, create own column for each
# drop the orignal Date column and check that the new columns are correct

burbank2018_df['Day'] = pd.DatetimeIndex(burbank2018_df['FlightDate']).day
burbank2018_df['Month'] = pd.DatetimeIndex(burbank2018_df['FlightDate']).month
burbank2018_df['Year'] = pd.DatetimeIndex(burbank2018_df['FlightDate']).year
burbank2018_df.drop(['FlightDate'], axis=1, inplace=True)
burbank2018_df

,DayOfWeek,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP,Dest_WIND,Dest_PRCP,Dest_SNOW,Dest_TEMP,Day,Month,Year
0,5,UA,BUR,CA,SFO,CA,2030,-16.0,0,326,2200,2153.0,-7.0,0,6.93,0.0,0.0,74.0,15.21,0.0,0.0,62.0,31,8,2018
1,5,UA,BUR,CA,SFO,CA,700,21.0,0,326,826,834.0,8.0,1,6.93,0.0,0.0,74.0,15.21,0.0,0.0,62.0,31,8,2018
2,5,UA,BUR,CA,DEN,CO,715,-2.0,0,850,1035,1032.0,-3.0,0,6.93,0.0,0.0,74.0,9.40,0.0,0.0,76.0,31,8,2018
3,4,UA,BUR,CA,SFO,CA,2030,-6.0,0,326,2200,2154.0,-6.0,0,7.38,0.0,0.0,75.5,11.18,0.0,0.0,65.0,30,8,2018
4,4,UA,BUR,CA,SFO,CA,700,-3.0,0,326,826,823.0,-3.0,0,7.38,0.0,0.0,75.5,11.18,0.0,0.0,65.0,30,8,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25222,2,UA,BUR,CA,SFO,CA,1956,126.0,0,326,2115,2313.0,118.0,1,8.05,0.0,0.0,68.5,14.09,0.0,0.0,60.0,19,6,2018
25223,2,UA,BUR,CA,SFO,CA,700,-2.0,0,326,835,815.0,-20.0,0,8.05,0.0,0.0,68.5,14.09,0.0,0.0,60.0,19,6,2018
25224,1,UA,BUR,CA,SFO,CA,1956,7.0,0,326,2115,2110.0,-5.0,0,11.18,0.0,0.0,65.0,12.75,0.0,0.0,65.0,18,6,2018
25225,1,UA,BUR,CA,SFO,CA,700,18.0,0,326,835,858.0,23.0,1,11.18,0.0,0.0,65.0,12.75,0.0,0.0,65.0,18,6,2018
25226,7,UA,BUR,CA,SFO,CA,1956,0.0,0,326,2115,2145.0,30.0,1,8.95,0.0,0.0,62.5,8.72,0.0,0.0,62.0,17,6,2018

In [44]:
# create dummy variables for the airlines

airline_df = pd.get_dummies(burbank2018_df['Reporting_Airline'], drop_first=True)
airline_df

       B6  OO  UA  WN
0       0   0   1   0
1       0   0   1   0
2       0   0   1   0
3       0   0   1   0
4       0   0   1   0
...    ..  ..  ..  ..
25222   0   0   1   0
25223   0   0   1   0
25224   0   0   1   0
25225   0   0   1   0
25226   0   0   1   0

[25227 rows x 4 columns]

In [45]:
# create dummy variables for the destination airports

dest_df = pd.get_dummies(burbank2018_df['Dest'], drop_first=True)
dest_df = dest_df.add_prefix('da_')
dest_df

,da_DEN,da_JFK,da_LAS,da_OAK,da_PDX,da_PHX,da_SEA,da_SFO,da_SJC,da_SLC,da_SMF
0,0,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,1,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
25222,0,0,0,0,0,0,0,1,0,0,0
25223,0,0,0,0,0,0,0,1,0,0,0
25224,0,0,0,0,0,0,0,1,0,0,0
25225,0,0,0,0,0,0,0,1,0,0,0
25226,0,0,0,0,0,0,0,1,0,0,0

In [46]:
# combine the dummy variables and the original dataframe

burbank2018_df = pd.concat([burbank2018_df, airline_df, dest_df], axis=1) 
burbank2018_df.drop(['Reporting_Airline', 'Dest'], inplace=True, axis=1)
burbank2018_df

,DayOfWeek,Origin,OriginState,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP,Dest_WIND,Dest_PRCP,Dest_SNOW,Dest_TEMP,Day,Month,Year,B6,OO,UA,WN,da_DEN,da_JFK,da_LAS,da_OAK,da_PDX,da_PHX,da_SEA,da_SFO,da_SJC,da_SLC,da_SMF
0,5,BUR,CA,CA,2030,-16.0,0,326,2200,2153.0,-7.0,0,6.93,0.0,0.0,74.0,15.21,0.0,0.0,62.0,31,8,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
1,5,BUR,CA,CA,700,21.0,0,326,826,834.0,8.0,1,6.93,0.0,0.0,74.0,15.21,0.0,0.0,62.0,31,8,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
2,5,BUR,CA,CO,715,-2.0,0,850,1035,1032.0,-3.0,0,6.93,0.0,0.0,74.0,9.40,0.0,0.0,76.0,31,8,2018,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0
3,4,BUR,CA,CA,2030,-6.0,0,326,2200,2154.0,-6.0,0,7.38,0.0,0.0,75.5,11.18,0.0,0.0,65.0,30,8,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
4,4,BUR,CA,CA,700,-3.0,0,326,826,823.0,-3.0,0,7.38,0.0,0.0,75.5,11.18,0.0,0.0,65.0,30,8,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25222,2,BUR,CA,CA,1956,126.0,0,326,2115,2313.0,118.0,1,8.05,0.0,0.0,68.5,14.09,0.0,0.0,60.0,19,6,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
25223,2,BUR,CA,CA,700,-2.0,0,326,835,815.0,-20.0,0,8.05,0.0,0.0,68.5,14.09,0.0,0.0,60.0,19,6,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
25224,1,BUR,CA,CA,1956,7.0,0,326,2115,2110.0,-5.0,0,11.18,0.0,0.0,65.0,12.75,0.0,0.0,65.0,18,6,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
25225,1,BUR,CA,CA,700,18.0,0,326,835,858.0,23.0,1,11.18,0.0,0.0,65.0,12.75,0.0,0.0,65.0,18,6,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
25226,7,BUR,CA,CA,1956,0.0,0,326,2115,2145.0,30.0,1,8.95,0.0,0.0,62.5,8.72,0.0,0.0,62.0,17,6,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0

In [47]:
# move the delayed (target) column to the end

delay_df = burbank2018_df.pop('Delayed')
burbank2018_df['Delayed'] = delay_df
burbank2018_df

,DayOfWeek,Origin,OriginState,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP,Dest_WIND,Dest_PRCP,Dest_SNOW,Dest_TEMP,Day,Month,Year,B6,OO,UA,WN,da_DEN,da_JFK,da_LAS,da_OAK,da_PDX,da_PHX,da_SEA,da_SFO,da_SJC,da_SLC,da_SMF,Delayed
0,5,BUR,CA,CA,2030,-16.0,0,326,2200,2153.0,-7.0,6.93,0.0,0.0,74.0,15.21,0.0,0.0,62.0,31,8,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
1,5,BUR,CA,CA,700,21.0,0,326,826,834.0,8.0,6.93,0.0,0.0,74.0,15.21,0.0,0.0,62.0,31,8,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1
2,5,BUR,CA,CO,715,-2.0,0,850,1035,1032.0,-3.0,6.93,0.0,0.0,74.0,9.40,0.0,0.0,76.0,31,8,2018,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0
3,4,BUR,CA,CA,2030,-6.0,0,326,2200,2154.0,-6.0,7.38,0.0,0.0,75.5,11.18,0.0,0.0,65.0,30,8,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
4,4,BUR,CA,CA,700,-3.0,0,326,826,823.0,-3.0,7.38,0.0,0.0,75.5,11.18,0.0,0.0,65.0,30,8,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25222,2,BUR,CA,CA,1956,126.0,0,326,2115,2313.0,118.0,8.05,0.0,0.0,68.5,14.09,0.0,0.0,60.0,19,6,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1
25223,2,BUR,CA,CA,700,-2.0,0,326,835,815.0,-20.0,8.05,0.0,0.0,68.5,14.09,0.0,0.0,60.0,19,6,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
25224,1,BUR,CA,CA,1956,7.0,0,326,2115,2110.0,-5.0,11.18,0.0,0.0,65.0,12.75,0.0,0.0,65.0,18,6,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
25225,1,BUR,CA,CA,700,18.0,0,326,835,858.0,23.0,11.18,0.0,0.0,65.0,12.75,0.0,0.0,65.0,18,6,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1
25226,7,BUR,CA,CA,1956,0.0,0,326,2115,2145.0,30.0,8.95,0.0,0.0,62.5,8.72,0.0,0.0,62.0,17,6,2018,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1

In [48]:
# look at the proportion of delayed flights

burbank2018_df['Delayed'].value_counts()

0    15738
1     9489
Name: Delayed, dtype: int64

In [49]:
# check that all values are numerical (float or int)

burbank2018_df.dtypes

DayOfWeek        int64
Origin          object
OriginState     object
DestState       object
CRSDepTime       int64
DepDelay       float64
Cancelled        int64
Distance         int64
CRSArrTime       int64
ArrTime        float64
ArrDelay       float64
Origin_WIND    float64
Origin_PRCP    float64
Origin_SNOW    float64
Origin_TEMP    float64
Dest_WIND      float64
Dest_PRCP      float64
Dest_SNOW      float64
Dest_TEMP      float64
Day              int64
Month            int64
Year             int64
B6               uint8
OO               uint8
UA               uint8
WN               uint8
da_DEN           uint8
da_JFK           uint8
da_LAS           uint8
da_OAK           uint8
da_PDX           uint8
da_PHX           uint8
da_SEA           uint8
da_SFO           uint8
da_SJC           uint8
da_SLC           uint8
da_SMF           uint8
Delayed          int64
dtype: object

In [50]:
# drop the Year. Origin and OriginState columns because they only have one value each
# drop information about actual arrival times (gives away too much information)

burbank2018_df.drop(columns=['Year',
                             'Origin',
                             'OriginState',
                            #'DepDelay',
                             'ArrTime',
                             'ArrDelay',
                             'DestState'], axis=1, inplace=True)
burbank2018_df

,DayOfWeek,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP,Dest_WIND,Dest_PRCP,Dest_SNOW,Dest_TEMP,Day,Month,B6,OO,UA,WN,da_DEN,da_JFK,da_LAS,da_OAK,da_PDX,da_PHX,da_SEA,da_SFO,da_SJC,da_SLC,da_SMF,Delayed
0,5,2030,-16.0,0,326,2200,6.93,0.0,0.0,74.0,15.21,0.0,0.0,62.0,31,8,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
1,5,700,21.0,0,326,826,6.93,0.0,0.0,74.0,15.21,0.0,0.0,62.0,31,8,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1
2,5,715,-2.0,0,850,1035,6.93,0.0,0.0,74.0,9.40,0.0,0.0,76.0,31,8,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0
3,4,2030,-6.0,0,326,2200,7.38,0.0,0.0,75.5,11.18,0.0,0.0,65.0,30,8,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
4,4,700,-3.0,0,326,826,7.38,0.0,0.0,75.5,11.18,0.0,0.0,65.0,30,8,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25222,2,1956,126.0,0,326,2115,8.05,0.0,0.0,68.5,14.09,0.0,0.0,60.0,19,6,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1
25223,2,700,-2.0,0,326,835,8.05,0.0,0.0,68.5,14.09,0.0,0.0,60.0,19,6,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
25224,1,1956,7.0,0,326,2115,11.18,0.0,0.0,65.0,12.75,0.0,0.0,65.0,18,6,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
25225,1,700,18.0,0,326,835,11.18,0.0,0.0,65.0,12.75,0.0,0.0,65.0,18,6,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1
25226,7,1956,0.0,0,326,2115,8.95,0.0,0.0,62.5,8.72,0.0,0.0,62.0,17,6,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1

In [51]:
# ensure all values are numerical

burbank2018_df.dtypes

DayOfWeek        int64
CRSDepTime       int64
DepDelay       float64
Cancelled        int64
Distance         int64
CRSArrTime       int64
Origin_WIND    float64
Origin_PRCP    float64
Origin_SNOW    float64
Origin_TEMP    float64
Dest_WIND      float64
Dest_PRCP      float64
Dest_SNOW      float64
Dest_TEMP      float64
Day              int64
Month            int64
B6               uint8
OO               uint8
UA               uint8
WN               uint8
da_DEN           uint8
da_JFK           uint8
da_LAS           uint8
da_OAK           uint8
da_PDX           uint8
da_PHX           uint8
da_SEA           uint8
da_SFO           uint8
da_SJC           uint8
da_SLC           uint8
da_SMF           uint8
Delayed          int64
dtype: object

In [52]:
burbank2018_df.to_csv('burbank2018.csv')