**Burbank 2019**
<br/>Create and clean a dataframe of the 2019 Burbank airport adding origin and destination weather.
<br/>Run a comparison of the airlines and destinations in 2018 and 2019 and adjust the dataframe accordingly.

In [1]:
import numpy as np
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
# increase display size to enable viewing of all data columns

pd.options.display.max_columns = 40

In [4]:
# read in the clean flights csv

flights2019_df = pd.read_csv('flights2019clean.csv')
flights2019_df.drop(['Unnamed: 0'], axis=1, inplace=True)
flights2019_df

,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Origin,OriginCityName,OriginState,Dest,DestCityName,DestState,CRSDepTime,DepTime,DepDelay,DepDel15,DepartureDelayGroups,TaxiOut,WheelsOff,Cancelled,CancellationCode,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,CRSArrTime,ArrTime,ArrDelay,Delayed
0,4,2019-08-01,DL,N354NW,ATL,"Atlanta, GA",GA,DFW,"Dallas/Fort Worth, TX",TX,1954,2025.0,31.0,1.0,2.0,17.0,2042.0,0,0,731,3,1.0,0.0,0.0,0.0,16.0,2114,2131.0,17.0,1
1,4,2019-08-01,DL,N320US,DFW,"Dallas/Fort Worth, TX",TX,ATL,"Atlanta, GA",GA,1709,1706.0,-3.0,0.0,-1.0,19.0,1725.0,0,0,731,3,0.0,0.0,0.0,0.0,0.0,2024,2012.0,-12.0,0
2,4,2019-08-01,DL,N931DN,IAH,"Houston, TX",TX,ATL,"Atlanta, GA",GA,1749,1829.0,40.0,1.0,2.0,12.0,1841.0,0,0,689,3,17.0,0.0,0.0,0.0,20.0,2102,2139.0,37.0,1
3,4,2019-08-01,DL,N851DN,PDX,"Portland, OR",OR,SLC,"Salt Lake City, UT",UT,1310,1306.0,-4.0,0.0,-1.0,13.0,1319.0,0,0,630,3,0.0,0.0,0.0,0.0,0.0,1601,1558.0,-3.0,0
4,4,2019-08-01,DL,N775DE,SLC,"Salt Lake City, UT",UT,PDX,"Portland, OR",OR,829,820.0,-9.0,0.0,-1.0,16.0,836.0,0,0,630,3,0.0,0.0,0.0,0.0,0.0,926,911.0,-15.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7419311,5,2019-11-08,DL,N978AT,HOU,"Houston, TX",TX,ATL,"Atlanta, GA",GA,1324,1320.0,-4.0,0.0,-1.0,14.0,1334.0,0,0,696,3,0.0,0.0,0.0,0.0,0.0,1624,1605.0,-19.0,0
7419312,5,2019-11-08,DL,N6716C,CHS,"Charleston, SC",SC,ATL,"Atlanta, GA",GA,700,719.0,19.0,1.0,1.0,10.0,729.0,0,0,259,2,0.0,0.0,0.0,0.0,0.0,817,820.0,3.0,1
7419313,5,2019-11-08,DL,N851DN,MSP,"Minneapolis, MN",MN,BWI,"Baltimore, MD",MD,1800,1754.0,-6.0,0.0,-1.0,22.0,1816.0,0,0,936,4,0.0,0.0,0.0,0.0,0.0,2130,2116.0,-14.0,0
7419314,5,2019-11-08,DL,N352NB,GEG,"Spokane, WA",WA,SLC,"Salt Lake City, UT",UT,1015,1009.0,-6.0,0.0,-1.0,11.0,1020.0,0,0,546,3,0.0,0.0,0.0,0.0,0.0,1258,1237.0,-21.0,0
7419315,5,2019-11-08,DL,N352NB,SLC,"Salt Lake City, UT",UT,GEG,"Spokane, WA",WA,844,836.0,-8.0,0.0,-1.0,14.0,850.0,0,0,546,3,0.0,0.0,0.0,0.0,0.0,932,913.0,-19.0,0

In [5]:
# create a dataframe of the flights originating in Burbank

burbank2019_df = flights2019_df[(flights2019_df['Origin'] == 'BUR')]
burbank2019_df

,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Origin,OriginCityName,OriginState,Dest,DestCityName,DestState,CRSDepTime,DepTime,DepDelay,DepDel15,DepartureDelayGroups,TaxiOut,WheelsOff,Cancelled,CancellationCode,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,CRSArrTime,ArrTime,ArrDelay,Delayed
1760,4,2019-08-01,DL,N306DQ,BUR,"Burbank, CA",CA,ATL,"Atlanta, GA",GA,1110,1119.0,9.0,0.0,0.0,19.0,1138.0,0,0,1941,8,0.0,0.0,0.0,0.0,0.0,1842,1854.0,12.0,1
3112,4,2019-08-01,DL,N309DE,BUR,"Burbank, CA",CA,ATL,"Atlanta, GA",GA,2130,48.0,198.0,1.0,12.0,18.0,106.0,0,0,1941,8,192.0,0.0,0.0,0.0,0.0,454,806.0,192.0,1
4918,5,2019-08-02,DL,N309DE,BUR,"Burbank, CA",CA,ATL,"Atlanta, GA",GA,1110,1127.0,17.0,1.0,1.0,14.0,1141.0,0,0,1941,8,0.0,0.0,15.0,0.0,0.0,1842,1857.0,15.0,1
6270,5,2019-08-02,DL,N310DE,BUR,"Burbank, CA",CA,ATL,"Atlanta, GA",GA,2130,2127.0,-3.0,0.0,-1.0,12.0,2139.0,0,0,1941,8,0.0,0.0,0.0,0.0,0.0,454,448.0,-6.0,0
7737,6,2019-08-03,DL,N301DQ,BUR,"Burbank, CA",CA,ATL,"Atlanta, GA",GA,1110,1105.0,-5.0,0.0,-1.0,17.0,1122.0,0,0,1941,8,0.0,0.0,0.0,0.0,0.0,1842,1828.0,-14.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7407883,6,2019-11-23,DL,N305DQ,BUR,"Burbank, CA",CA,ATL,"Atlanta, GA",GA,1120,1120.0,0.0,0.0,0.0,15.0,1135.0,0,0,1941,8,0.0,0.0,0.0,0.0,0.0,1835,1822.0,-13.0,0
7410341,7,2019-11-24,DL,N308DE,BUR,"Burbank, CA",CA,ATL,"Atlanta, GA",GA,1124,1123.0,-1.0,0.0,-1.0,23.0,1146.0,0,0,1941,8,0.0,0.0,0.0,0.0,0.0,1841,1829.0,-12.0,0
7412800,1,2019-11-25,DL,N305DQ,BUR,"Burbank, CA",CA,ATL,"Atlanta, GA",GA,1124,1125.0,1.0,0.0,0.0,22.0,1147.0,0,0,1941,8,0.0,0.0,0.0,0.0,0.0,1841,1822.0,-19.0,0
7417446,4,2019-11-07,DL,N310DE,BUR,"Burbank, CA",CA,ATL,"Atlanta, GA",GA,1124,1122.0,-2.0,0.0,-1.0,20.0,1142.0,0,0,1941,8,0.0,0.0,0.0,0.0,0.0,1841,1823.0,-18.0,0
7417697,5,2019-11-08,DL,N307DQ,BUR,"Burbank, CA",CA,ATL,"Atlanta, GA",GA,2159,2151.0,-8.0,0.0,-1.0,15.0,2206.0,0,0,1941,8,0.0,0.0,0.0,0.0,0.0,510,450.0,-20.0,0

In [6]:
# read in the burbank 2018 file to be used to compare data points

burbank2018_df = pd.read_csv('burbank2018comp.csv')
burbank2018_df.drop(['Unnamed: 0'], axis=1, inplace=True)
burbank2018_df

,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Origin,OriginCityName,OriginState,Dest,DestCityName,DestState,CRSDepTime,DepTime,DepDelay,DepDel15,DepartureDelayGroups,TaxiOut,WheelsOff,Cancelled,CancellationCode,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,CRSArrTime,ArrTime,ArrDelay,Delayed
0,5,2018-08-31,UA,N899UA,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,2030,2014.0,-16.0,0.0,-2.0,18.0,2032.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,2200,2153.0,-7.0,0
1,5,2018-08-31,UA,N35204,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,700,721.0,21.0,1.0,1.0,13.0,734.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,826,834.0,8.0,1
2,5,2018-08-31,UA,N810UA,BUR,"Burbank, CA",CA,DEN,"Denver, CO",CO,715,713.0,-2.0,0.0,-1.0,12.0,725.0,0,0,850,4,0.0,0.0,0.0,0.0,0.0,1035,1032.0,-3.0,0
3,4,2018-08-30,UA,N833UA,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,2030,2024.0,-6.0,0.0,-1.0,16.0,2040.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,2200,2154.0,-6.0,0
4,4,2018-08-30,UA,N76505,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,700,657.0,-3.0,0.0,-1.0,22.0,719.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,826,823.0,-3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25222,2,2018-06-19,UA,N26226,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,1956,2202.0,126.0,1.0,8.0,13.0,2215.0,0,0,326,2,0.0,0.0,0.0,0.0,118.0,2115,2313.0,118.0,1
25223,2,2018-06-19,UA,N26215,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,700,658.0,-2.0,0.0,-1.0,19.0,717.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,835,815.0,-20.0,0
25224,1,2018-06-18,UA,N77536,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,1956,2003.0,7.0,1.0,0.0,11.0,2014.0,0,0,326,2,0.0,0.0,0.0,0.0,0.0,2115,2110.0,-5.0,0
25225,1,2018-06-18,UA,N35271,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,700,718.0,18.0,1.0,1.0,39.0,757.0,0,0,326,2,0.0,0.0,23.0,0.0,0.0,835,858.0,23.0,1
25226,7,2018-06-17,UA,N77258,BUR,"Burbank, CA",CA,SFO,"San Francisco, CA",CA,1956,1956.0,0.0,0.0,0.0,14.0,2010.0,0,0,326,2,0.0,0.0,30.0,0.0,0.0,2115,2145.0,30.0,1

In [7]:
# check to see whether 2018 and 2019 have the same number of unique destinations

print('2018: ' + str(burbank2018_df['Dest'].nunique()))
print('2019: ' + str(burbank2019_df['Dest'].nunique()))
print('Difference: ' + str(burbank2019_df['Dest'].nunique() - burbank2018_df['Dest'].nunique()))

2018: 12
2019: 18
Difference: 6

In [8]:
# create a new dataframe with the 2018 and 2019 destinations

comparison_df = pd.DataFrame()
comparison_df['Dest19'] = burbank2019_df['Dest']
comparison_df.reset_index(drop=True, inplace=True)
comparison_df['Dest17'] = burbank2018_df['Dest']
comparison_df

      Dest19 Dest17
0        ATL    SFO
1        ATL    SFO
2        ATL    DEN
3        ATL    SFO
4        ATL    SFO
...      ...    ...
31897    ATL    NaN
31898    ATL    NaN
31899    ATL    NaN
31900    ATL    NaN
31901    ATL    NaN

[31902 rows x 2 columns]

In [9]:
# check to see which destinations exist in 2018, but not 2019

comparison_df['Unique'] = comparison_df['Dest17'][~comparison_df['Dest17'].isin(comparison_df['Dest19'])].drop_duplicates()
display(comparison_df['Unique'].nunique())

difference_df = pd.DataFrame()
difference_df = comparison_df['Unique'].value_counts()
difference = difference_df.index.to_list()
difference

0

[]

In [10]:
# check to see which destinations exist in 2019, but not 2018

comparison_df['Unique'] = comparison_df['Dest19'][~comparison_df['Dest19'].isin(comparison_df['Dest17'])].drop_duplicates()
display(comparison_df['Unique'].nunique())

difference_df = pd.DataFrame(columns=['Destination', 'Occurence'])
difference_df = comparison_df['Unique'].value_counts()
difference = difference_df.index.to_list()
difference

6

['HOU', 'BOS', 'DFW', 'BNA', 'MDW', 'ATL']

In [11]:
# drop any rows pertaining to HOU, MDW or BOS

burbank2019_df = burbank2019_df.drop(burbank2019_df[(burbank2019_df['Dest'] == 'ATL')].index)
burbank2019_df = burbank2019_df.drop(burbank2019_df[(burbank2019_df['Dest'] == 'BOS')].index)
burbank2019_df = burbank2019_df.drop(burbank2019_df[(burbank2019_df['Dest'] == 'MDW')].index)
burbank2019_df = burbank2019_df.drop(burbank2019_df[(burbank2019_df['Dest'] == 'HOU')].index)
burbank2019_df = burbank2019_df.drop(burbank2019_df[(burbank2019_df['Dest'] == 'BNA')].index)
burbank2019_df = burbank2019_df.drop(burbank2019_df[(burbank2019_df['Dest'] == 'DFW')].index)
burbank2019_df['Dest'].value_counts()

SJC    4512
OAK    4350
LAS    3921
SFO    3719
PHX    3599
SMF    3258
DEN    1703
SLC    1375
SEA    1300
PDX    1208
JFK     636
DAL     397
Name: Dest, dtype: int64

In [12]:
# check to see whether 2018 and 2019 have the same number of unique reporting airlines

print('2018: ' + str(burbank2018_df['Reporting_Airline'].nunique()))
print('2019: ' + str(burbank2019_df['Reporting_Airline'].nunique()))
print('Difference: ' + str(burbank2019_df['Reporting_Airline'].nunique() - burbank2018_df['Reporting_Airline'].nunique()))

2018: 5
2019: 8
Difference: 3

In [13]:
# create a new dataframe with the 2018 and 2019 reporting airlines

comparison_df = pd.DataFrame()
comparison_df['Airline19'] = burbank2019_df['Reporting_Airline']
comparison_df.reset_index(drop=True, inplace=True)
comparison_df['Airline17'] = burbank2018_df['Reporting_Airline']
comparison_df

      Airline19 Airline17
0            YV        UA
1            YV        UA
2            YV        UA
3            YV        UA
4            YV        UA
...         ...       ...
29973        B6       NaN
29974        B6       NaN
29975        B6       NaN
29976        B6       NaN
29977        B6       NaN

[29978 rows x 2 columns]

In [14]:
# check to see which reporting airlines exist in 2018, but not 2019

comparison_df['Unique'] = comparison_df['Airline17'][~comparison_df['Airline17'].isin(comparison_df['Airline19'])].drop_duplicates()
display(comparison_df['Unique'].nunique())

difference_df = pd.DataFrame()
difference_df = comparison_df['Unique'].value_counts()
difference = difference_df.index.to_list()
difference

0

[]

In [15]:
# check to see which destinations exist in 2019, but not 2018

comparison_df['Unique'] = comparison_df['Airline19'][~comparison_df['Airline19'].isin(comparison_df['Airline17'])].drop_duplicates()
display(comparison_df['Unique'].nunique())

difference_df = pd.DataFrame(columns=['Destination', 'Occurence'])
difference_df = comparison_df['Unique'].value_counts()
difference = difference_df.index.to_list()
difference

3

['YV', 'AA', 'NK']

In [16]:
# drop any rows pertaining to HOU, MDW or BOSburbank2019_df = burbank2019_df.drop(burbank2019_df[(burbank2019_df['Reporting_Airline'] == 'YV')].index)

burbank2019_df = burbank2019_df.drop(burbank2019_df[(burbank2019_df['Reporting_Airline'] == 'NK')].index)
burbank2019_df = burbank2019_df.drop(burbank2019_df[(burbank2019_df['Reporting_Airline'] == 'YV')].index)
burbank2019_df = burbank2019_df.drop(burbank2019_df[(burbank2019_df['Reporting_Airline'] == 'AA')].index)
burbank2019_df['Reporting_Airline'].value_counts()

WN    20492
OO     4920
AS     1574
UA      667
B6      636
Name: Reporting_Airline, dtype: int64

In [17]:
# review the dataframe

burbank2019_df

,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Origin,OriginCityName,OriginState,Dest,DestCityName,DestState,CRSDepTime,DepTime,DepDelay,DepDel15,DepartureDelayGroups,TaxiOut,WheelsOff,Cancelled,CancellationCode,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,CRSArrTime,ArrTime,ArrDelay,Delayed
149422,4,2019-08-01,AS,N215AK,BUR,"Burbank, CA",CA,SEA,"Seattle, WA",WA,1405,1411.0,6.0,0.0,0.0,17.0,1428.0,0,0,937,4,0.0,0.0,0.0,0.0,0.0,1645,1641.0,-4.0,0
149445,4,2019-08-01,AS,N408AS,BUR,"Burbank, CA",CA,PDX,"Portland, OR",OR,1710,1716.0,6.0,0.0,0.0,15.0,1731.0,0,0,817,4,0.0,0.0,0.0,0.0,0.0,1920,1917.0,-3.0,0
149464,4,2019-08-01,AS,N479AS,BUR,"Burbank, CA",CA,SEA,"Seattle, WA",WA,1925,1923.0,-2.0,0.0,-1.0,14.0,1937.0,0,0,937,4,0.0,0.0,0.0,0.0,0.0,2205,2208.0,3.0,1
149663,4,2019-08-01,AS,N284VA,BUR,"Burbank, CA",CA,SEA,"Seattle, WA",WA,800,753.0,-7.0,0.0,-1.0,31.0,824.0,0,0,937,4,0.0,0.0,0.0,0.0,0.0,1040,1042.0,2.0,1
149666,4,2019-08-01,AS,N637VA,BUR,"Burbank, CA",CA,SEA,"Seattle, WA",WA,1050,1049.0,-1.0,0.0,-1.0,14.0,1103.0,0,0,937,4,0.0,0.0,0.0,0.0,0.0,1330,1321.0,-9.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7388634,1,2019-11-18,B6,N644JB,BUR,"Burbank, CA",CA,JFK,"New York, NY",NY,2107,2058.0,-9.0,0.0,-1.0,19.0,2117.0,0,0,2465,10,0.0,0.0,0.0,0.0,0.0,521,515.0,-6.0,0
7389258,1,2019-11-18,B6,N789JB,BUR,"Burbank, CA",CA,JFK,"New York, NY",NY,1445,1452.0,7.0,0.0,0.0,25.0,1517.0,0,0,2465,10,7.0,0.0,18.0,0.0,0.0,2300,2325.0,25.0,1
7389472,2,2019-11-19,B6,N629JB,BUR,"Burbank, CA",CA,JFK,"New York, NY",NY,2107,2056.0,-11.0,0.0,-1.0,16.0,2112.0,0,0,2465,10,0.0,0.0,0.0,0.0,0.0,521,458.0,-23.0,0
7390674,5,2019-11-29,B6,N706JB,BUR,"Burbank, CA",CA,JFK,"New York, NY",NY,1435,1448.0,13.0,0.0,0.0,19.0,1507.0,0,0,2465,10,0.0,0.0,0.0,0.0,0.0,2250,2226.0,-24.0,0
7390891,6,2019-11-30,B6,N794JB,BUR,"Burbank, CA",CA,JFK,"New York, NY",NY,2107,2108.0,1.0,0.0,0.0,15.0,2123.0,0,0,2465,10,0.0,0.0,0.0,0.0,0.0,521,458.0,-23.0,0

In [18]:
# drop columns with redundant, 'give-away', or unuseful information

burbank2019_df.drop(['Tail_Number', 
                     'OriginCityName', 
                     'DestCityName',
                     'DepTime', 
                     'DepDel15', 
                     'DepartureDelayGroups', 
                     'TaxiOut', 
                     'WheelsOff',
                     'DistanceGroup',
                     'CarrierDelay',
                     'WeatherDelay',
                     'NASDelay',
                     'SecurityDelay',
                     'LateAircraftDelay',
                     'CancellationCode'], inplace=True, axis=1)
burbank2019_df

,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed
149422,4,2019-08-01,AS,BUR,CA,SEA,WA,1405,6.0,0,937,1645,1641.0,-4.0,0
149445,4,2019-08-01,AS,BUR,CA,PDX,OR,1710,6.0,0,817,1920,1917.0,-3.0,0
149464,4,2019-08-01,AS,BUR,CA,SEA,WA,1925,-2.0,0,937,2205,2208.0,3.0,1
149663,4,2019-08-01,AS,BUR,CA,SEA,WA,800,-7.0,0,937,1040,1042.0,2.0,1
149666,4,2019-08-01,AS,BUR,CA,SEA,WA,1050,-1.0,0,937,1330,1321.0,-9.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7388634,1,2019-11-18,B6,BUR,CA,JFK,NY,2107,-9.0,0,2465,521,515.0,-6.0,0
7389258,1,2019-11-18,B6,BUR,CA,JFK,NY,1445,7.0,0,2465,2300,2325.0,25.0,1
7389472,2,2019-11-19,B6,BUR,CA,JFK,NY,2107,-11.0,0,2465,521,458.0,-23.0,0
7390674,5,2019-11-29,B6,BUR,CA,JFK,NY,1435,13.0,0,2465,2250,2226.0,-24.0,0
7390891,6,2019-11-30,B6,BUR,CA,JFK,NY,2107,1.0,0,2465,521,458.0,-23.0,0

In [19]:
# summary statistics for the dataframe

burbank2019_df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
DayOfWeek,28289.0,3.829404,1.973781,1.0,2.0,4.0,5.0,7.0
CRSDepTime,28289.0,1358.081763,452.116284,645.0,945.0,1335.0,1735.0,2159.0
DepDelay,28289.0,7.927746,35.847463,-29.0,-5.0,-1.0,5.0,1276.0
Cancelled,28289.0,0.035738,0.185640,0.0,0.0,0.0,0.0,1.0
Distance,28289.0,469.349924,377.894001,223.0,296.0,326.0,369.0,2465.0
CRSArrTime,28289.0,1508.109300,457.537126,5.0,1114.0,1505.0,1915.0,2355.0
ArrTime,28289.0,1444.612075,543.744073,0.0,1040.0,1445.0,1909.0,2400.0
ArrDelay,28289.0,2.294920,54.580041,-2232.0,-13.0,-5.0,4.0,1267.0
Delayed,28289.0,0.317155,0.465377,0.0,0.0,0.0,1.0,1.0

In [20]:
# import all the weather data

weather_df = pd.read_csv('data/weather/all13_weather.csv')
weather_df

,STATION,NAME,AIRPORT,DATE,AWND,PGTM,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,TOBS,WDF2,WDF5,WSF2,WSF5
0,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2017-01-01,9.62,NaN,0.43,3.0,2.0,35.0,37.0,28.0,NaN,10.0,10.0,16.1,19.0
1,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2017-01-02,10.51,NaN,0.00,0.0,2.0,32.0,34.0,26.0,NaN,70.0,60.0,15.0,19.0
2,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2017-01-03,11.86,NaN,0.00,0.0,2.0,27.0,33.0,21.0,NaN,20.0,20.0,18.1,21.9
3,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2017-01-04,10.96,NaN,0.00,0.0,1.2,27.0,36.0,22.0,NaN,20.0,20.0,16.1,19.0
4,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2017-01-05,5.82,NaN,0.00,0.0,0.0,28.0,35.0,21.0,NaN,40.0,40.0,15.0,16.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14230,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-27,11.41,838.0,0.00,NaN,NaN,NaN,53.0,34.0,NaN,290.0,280.0,23.0,28.0
14231,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-28,6.04,8.0,0.00,NaN,NaN,NaN,40.0,30.0,NaN,100.0,290.0,12.1,15.0
14232,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-29,8.28,1055.0,0.87,NaN,NaN,NaN,44.0,36.0,NaN,110.0,100.0,19.9,27.1
14233,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-30,16.11,1238.0,0.44,NaN,NaN,NaN,44.0,31.0,NaN,220.0,220.0,29.1,44.1
14234,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-31,13.65,659.0,0.00,NaN,NaN,NaN,32.0,27.0,NaN,240.0,250.0,25.9,38.0

In [21]:
# create a dataframe of the 2019 weather

weather2019_df = weather_df[(pd.DatetimeIndex(weather_df['DATE']).year == 2019)]
weather2019_df

,STATION,NAME,AIRPORT,DATE,AWND,PGTM,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,TOBS,WDF2,WDF5,WSF2,WSF5
730,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2019-01-01,2.01,NaN,0.00,0.0,0.0,38.0,44.0,33.0,NaN,120.0,110.0,8.1,11.0
731,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2019-01-02,6.93,NaN,0.04,0.0,0.0,37.0,47.0,32.0,NaN,220.0,210.0,14.1,19.9
732,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2019-01-03,11.18,NaN,0.78,0.0,0.0,47.0,56.0,43.0,NaN,190.0,190.0,30.0,36.9
733,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2019-01-04,11.41,NaN,0.08,0.0,0.0,51.0,51.0,46.0,NaN,200.0,200.0,25.1,35.1
734,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2019-01-05,4.03,NaN,0.04,0.0,0.0,46.0,51.0,41.0,NaN,80.0,90.0,14.1,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14230,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-27,11.41,838.0,0.00,NaN,NaN,NaN,53.0,34.0,NaN,290.0,280.0,23.0,28.0
14231,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-28,6.04,8.0,0.00,NaN,NaN,NaN,40.0,30.0,NaN,100.0,290.0,12.1,15.0
14232,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-29,8.28,1055.0,0.87,NaN,NaN,NaN,44.0,36.0,NaN,110.0,100.0,19.9,27.1
14233,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-30,16.11,1238.0,0.44,NaN,NaN,NaN,44.0,31.0,NaN,220.0,220.0,29.1,44.1
14234,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-31,13.65,659.0,0.00,NaN,NaN,NaN,32.0,27.0,NaN,240.0,250.0,25.9,38.0

In [22]:
# look at the total number of NaN values for each column

weather2019_df.isna().sum()

STATION       0
NAME          0
AIRPORT       0
DATE          0
AWND          0
PGTM       4196
PRCP          1
SNOW       1106
SNWD       1067
TAVG       1460
TMAX          0
TMIN          4
TOBS       4382
WDF2        730
WDF5        738
WSF2        730
WSF5        738
dtype: int64

In [23]:
# TMIN will be used to generate missing values for TAVG and are only missing a few values -- fill using forward fill

weather2019_df['TMAX'].ffill(inplace=True)
weather2019_df['TMIN'].ffill(inplace=True)
weather2019_df.isna().sum()

STATION       0
NAME          0
AIRPORT       0
DATE          0
AWND          0
PGTM       4196
PRCP          1
SNOW       1106
SNWD       1067
TAVG       1460
TMAX          0
TMIN          0
TOBS       4382
WDF2        730
WDF5        738
WSF2        730
WSF5        738
dtype: int64

In [24]:
# create a temporary column calculating the average temperature using TMAX and TMIN

weather2019_df['temp_avg'] = (weather2019_df['TMAX'] + weather2019_df['TMIN']) / 2
weather2019_df

,STATION,NAME,AIRPORT,DATE,AWND,PGTM,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,TOBS,WDF2,WDF5,WSF2,WSF5,temp_avg
730,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2019-01-01,2.01,NaN,0.00,0.0,0.0,38.0,44.0,33.0,NaN,120.0,110.0,8.1,11.0,38.5
731,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2019-01-02,6.93,NaN,0.04,0.0,0.0,37.0,47.0,32.0,NaN,220.0,210.0,14.1,19.9,39.5
732,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2019-01-03,11.18,NaN,0.78,0.0,0.0,47.0,56.0,43.0,NaN,190.0,190.0,30.0,36.9,49.5
733,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2019-01-04,11.41,NaN,0.08,0.0,0.0,51.0,51.0,46.0,NaN,200.0,200.0,25.1,35.1,48.5
734,USW00024233,"SEATTLE TACOMA INTERNATIONAL AIRPORT, WA US",SEA,2019-01-05,4.03,NaN,0.04,0.0,0.0,46.0,51.0,41.0,NaN,80.0,90.0,14.1,17.0,46.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14230,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-27,11.41,838.0,0.00,NaN,NaN,NaN,53.0,34.0,NaN,290.0,280.0,23.0,28.0,43.5
14231,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-28,6.04,8.0,0.00,NaN,NaN,NaN,40.0,30.0,NaN,100.0,290.0,12.1,15.0,35.0
14232,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-29,8.28,1055.0,0.87,NaN,NaN,NaN,44.0,36.0,NaN,110.0,100.0,19.9,27.1,40.0
14233,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-30,16.11,1238.0,0.44,NaN,NaN,NaN,44.0,31.0,NaN,220.0,220.0,29.1,44.1,37.5
14234,USW00094817,"PONTIAC OAKLAND CO INTERNATIONAL AIRPORT, MI US",OAK,2019-12-31,13.65,659.0,0.00,NaN,NaN,NaN,32.0,27.0,NaN,240.0,250.0,25.9,38.0,29.5

In [25]:
# fill in the missing TAVG values using the newly created average temperature column

weather2019_df['TAVG'].fillna(weather2019_df['temp_avg'], inplace=True)
weather2019_df.isna().sum()

STATION        0
NAME           0
AIRPORT        0
DATE           0
AWND           0
PGTM        4196
PRCP           1
SNOW        1106
SNWD        1067
TAVG           0
TMAX           0
TMIN           0
TOBS        4382
WDF2         730
WDF5         738
WSF2         730
WSF5         738
temp_avg       0
dtype: int64

In [26]:
# drop unnecessary and/or redundant columns

weather2019_df.drop(['STATION', 
                     'NAME', 
                     'PGTM', 
                     'SNWD', 
                     'TMAX', 
                     'TMIN', 
                     'TOBS', 
                     'WDF2', 
                     'WDF5', 
                     'WSF2', 
                     'WSF5',
                     'temp_avg'], axis=1, inplace=True)
weather2019_df

      AIRPORT        DATE   AWND  PRCP  SNOW  TAVG
730       SEA  2019-01-01   2.01  0.00   0.0  38.0
731       SEA  2019-01-02   6.93  0.04   0.0  37.0
732       SEA  2019-01-03  11.18  0.78   0.0  47.0
733       SEA  2019-01-04  11.41  0.08   0.0  51.0
734       SEA  2019-01-05   4.03  0.04   0.0  46.0
...       ...         ...    ...   ...   ...   ...
14230     OAK  2019-12-27  11.41  0.00   NaN  43.5
14231     OAK  2019-12-28   6.04  0.00   NaN  35.0
14232     OAK  2019-12-29   8.28  0.87   NaN  40.0
14233     OAK  2019-12-30  16.11  0.44   NaN  37.5
14234     OAK  2019-12-31  13.65  0.00   NaN  29.5

[4745 rows x 6 columns]

In [27]:
# check for any remaining NaN values

weather2019_df.isna().sum()

AIRPORT       0
DATE          0
AWND          0
PRCP          1
SNOW       1106
TAVG          0
dtype: int64

In [28]:
# investigate which airports are missing values for SNOW

weather2019_df['AIRPORT'][(weather2019_df['SNOW'].isna())].value_counts()

OAK    365
BUR    365
SJC    315
SFO     32
SMF     18
LAS      5
PHX      4
JFK      1
SLC      1
Name: AIRPORT, dtype: int64

In [29]:
# all airports in warm climates where snow is unlikely... so input zeros for the NaNs

weather2019_df['SNOW'].fillna(0, inplace=True)
weather2019_df.isna().sum()

AIRPORT    0
DATE       0
AWND       0
PRCP       1
SNOW       0
TAVG       0
dtype: int64

In [30]:
# investigate the row missing precipitation information

weather2019_df[(weather2019_df['PRCP'].isna())]

      AIRPORT        DATE   AWND  PRCP  SNOW  TAVG
13879     OAK  2019-01-10  13.42   NaN   0.0  22.0

In [31]:
# fill in these missing values using forward fill

weather2019_df['PRCP'].ffill(inplace=True)
weather2019_df.isna().sum()

AIRPORT    0
DATE       0
AWND       0
PRCP       0
SNOW       0
TAVG       0
dtype: int64

In [32]:
# rename the columns with more intuitive names

weather2019_df.columns = ['AIRPORT', 
                          'DATE', 
                          'WIND', 
                          'PRCP', 
                          'SNOW', 
                          'TEMP']
weather2019_df

      AIRPORT        DATE   WIND  PRCP  SNOW  TEMP
730       SEA  2019-01-01   2.01  0.00   0.0  38.0
731       SEA  2019-01-02   6.93  0.04   0.0  37.0
732       SEA  2019-01-03  11.18  0.78   0.0  47.0
733       SEA  2019-01-04  11.41  0.08   0.0  51.0
734       SEA  2019-01-05   4.03  0.04   0.0  46.0
...       ...         ...    ...   ...   ...   ...
14230     OAK  2019-12-27  11.41  0.00   0.0  43.5
14231     OAK  2019-12-28   6.04  0.00   0.0  35.0
14232     OAK  2019-12-29   8.28  0.87   0.0  40.0
14233     OAK  2019-12-30  16.11  0.44   0.0  37.5
14234     OAK  2019-12-31  13.65  0.00   0.0  29.5

[4745 rows x 6 columns]

In [33]:
# ensure that the date column in both datafranes is of type datetime

pd.to_datetime(burbank2019_df['FlightDate'])
pd.to_datetime(weather2019_df['DATE'])

730     2019-01-01
731     2019-01-02
732     2019-01-03
733     2019-01-04
734     2019-01-05
           ...
14230   2019-12-27
14231   2019-12-28
14232   2019-12-29
14233   2019-12-30
14234   2019-12-31
Name: DATE, Length: 4745, dtype: datetime64[ns]

In [34]:
# ensure there is an entire year of data

display(burbank2019_df['FlightDate'].min())
display(burbank2019_df['FlightDate'].max())

'2019-01-01'

'2019-12-31'

In [35]:
# add in the origin airport weather to the burbank dataframe

burbank2019_df = pd.merge(burbank2019_df, weather2019_df, left_on=['FlightDate', 'Origin'], right_on=['DATE', 'AIRPORT'], how='left')
burbank2019_df.drop(columns=['AIRPORT', 'DATE'], axis=1, inplace=True)
burbank2019_df

,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,WIND,PRCP,SNOW,TEMP
0,4,2019-08-01,AS,BUR,CA,SEA,WA,1405,6.0,0,937,1645,1641.0,-4.0,0,8.50,0.00,0.0,76.5
1,4,2019-08-01,AS,BUR,CA,PDX,OR,1710,6.0,0,817,1920,1917.0,-3.0,0,8.50,0.00,0.0,76.5
2,4,2019-08-01,AS,BUR,CA,SEA,WA,1925,-2.0,0,937,2205,2208.0,3.0,1,8.50,0.00,0.0,76.5
3,4,2019-08-01,AS,BUR,CA,SEA,WA,800,-7.0,0,937,1040,1042.0,2.0,1,8.50,0.00,0.0,76.5
4,4,2019-08-01,AS,BUR,CA,SEA,WA,1050,-1.0,0,937,1330,1321.0,-9.0,0,8.50,0.00,0.0,76.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28284,1,2019-11-18,B6,BUR,CA,JFK,NY,2107,-9.0,0,2465,521,515.0,-6.0,0,6.71,0.00,0.0,72.5
28285,1,2019-11-18,B6,BUR,CA,JFK,NY,1445,7.0,0,2465,2300,2325.0,25.0,1,6.71,0.00,0.0,72.5
28286,2,2019-11-19,B6,BUR,CA,JFK,NY,2107,-11.0,0,2465,521,458.0,-23.0,0,6.93,0.00,0.0,67.5
28287,5,2019-11-29,B6,BUR,CA,JFK,NY,1435,13.0,0,2465,2250,2226.0,-24.0,0,8.28,0.00,0.0,48.0
28288,6,2019-11-30,B6,BUR,CA,JFK,NY,2107,1.0,0,2465,521,458.0,-23.0,0,6.04,0.06,0.0,46.0

In [36]:
# ensure the start and end dates are still correct

display(burbank2019_df['FlightDate'].min())
display(burbank2019_df['FlightDate'].max())

'2019-01-01'

'2019-12-31'

In [37]:
# check that the new columns have the correct values for Jan 1, 2019

burbank2019_df[(burbank2019_df['FlightDate'] == '2019-01-01')].head()

,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,WIND,PRCP,SNOW,TEMP
5303,2,2019-01-01,OO,BUR,CA,SJC,CA,1435,9.0,0,296,1550,1548.0,-2.0,0,6.26,0.0,0.0,51.0
5304,2,2019-01-01,OO,BUR,CA,SLC,UT,710,-9.0,0,574,1014,1003.0,-11.0,0,6.26,0.0,0.0,51.0
5305,2,2019-01-01,OO,BUR,CA,SLC,UT,1310,26.0,0,574,1608,1636.0,28.0,1,6.26,0.0,0.0,51.0
5306,2,2019-01-01,OO,BUR,CA,DEN,CO,1545,46.0,0,850,1920,2047.0,87.0,1,6.26,0.0,0.0,51.0
5307,2,2019-01-01,OO,BUR,CA,DEN,CO,700,-10.0,0,850,1036,1026.0,-10.0,0,6.26,0.0,0.0,51.0

In [38]:
# rename the new weather columns so that we know they pertain to the origin airport

burbank2019_df.rename(columns={'WIND' : 'Origin_WIND',
                               'PRCP' : 'Origin_PRCP',
                               'SNOW' : 'Origin_SNOW',
                               'TEMP' : 'Origin_TEMP'}, inplace=True)
burbank2019_df.head()

,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP
0,4,2019-08-01,AS,BUR,CA,SEA,WA,1405,6.0,0,937,1645,1641.0,-4.0,0,8.5,0.0,0.0,76.5
1,4,2019-08-01,AS,BUR,CA,PDX,OR,1710,6.0,0,817,1920,1917.0,-3.0,0,8.5,0.0,0.0,76.5
2,4,2019-08-01,AS,BUR,CA,SEA,WA,1925,-2.0,0,937,2205,2208.0,3.0,1,8.5,0.0,0.0,76.5
3,4,2019-08-01,AS,BUR,CA,SEA,WA,800,-7.0,0,937,1040,1042.0,2.0,1,8.5,0.0,0.0,76.5
4,4,2019-08-01,AS,BUR,CA,SEA,WA,1050,-1.0,0,937,1330,1321.0,-9.0,0,8.5,0.0,0.0,76.5

In [39]:
# add in the destination airport weather

burbank2019_df = pd.merge(burbank2019_df, weather2019_df, left_on=['FlightDate', 'Dest'], right_on=['DATE', 'AIRPORT'], how='left')
burbank2019_df.drop(columns=['AIRPORT', 'DATE'], axis=1, inplace=True)
burbank2019_df

,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP,WIND,PRCP,SNOW,TEMP
0,4,2019-08-01,AS,BUR,CA,SEA,WA,1405,6.0,0,937,1645,1641.0,-4.0,0,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0
1,4,2019-08-01,AS,BUR,CA,PDX,OR,1710,6.0,0,817,1920,1917.0,-3.0,0,8.50,0.00,0.0,76.5,5.14,0.00,0.0,74.0
2,4,2019-08-01,AS,BUR,CA,SEA,WA,1925,-2.0,0,937,2205,2208.0,3.0,1,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0
3,4,2019-08-01,AS,BUR,CA,SEA,WA,800,-7.0,0,937,1040,1042.0,2.0,1,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0
4,4,2019-08-01,AS,BUR,CA,SEA,WA,1050,-1.0,0,937,1330,1321.0,-9.0,0,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28284,1,2019-11-18,B6,BUR,CA,JFK,NY,2107,-9.0,0,2465,521,515.0,-6.0,0,6.71,0.00,0.0,72.5,11.41,0.46,0.0,40.0
28285,1,2019-11-18,B6,BUR,CA,JFK,NY,1445,7.0,0,2465,2300,2325.0,25.0,1,6.71,0.00,0.0,72.5,11.41,0.46,0.0,40.0
28286,2,2019-11-19,B6,BUR,CA,JFK,NY,2107,-11.0,0,2465,521,458.0,-23.0,0,6.93,0.00,0.0,67.5,8.28,0.17,0.0,44.0
28287,5,2019-11-29,B6,BUR,CA,JFK,NY,1435,13.0,0,2465,2250,2226.0,-24.0,0,8.28,0.00,0.0,48.0,16.55,0.00,0.0,37.0
28288,6,2019-11-30,B6,BUR,CA,JFK,NY,2107,1.0,0,2465,521,458.0,-23.0,0,6.04,0.06,0.0,46.0,10.96,0.00,0.0,36.0

In [40]:
# rename the new weather columns so that we know they pertain to the destination airport

burbank2019_df.rename(columns={'WIND' : 'Dest_WIND',
                               'PRCP' : 'Dest_PRCP',
                               'SNOW' : 'Dest_SNOW',
                               'TEMP' : 'Dest_TEMP'}, inplace=True)                               
burbank2019_df

,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP,Dest_WIND,Dest_PRCP,Dest_SNOW,Dest_TEMP
0,4,2019-08-01,AS,BUR,CA,SEA,WA,1405,6.0,0,937,1645,1641.0,-4.0,0,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0
1,4,2019-08-01,AS,BUR,CA,PDX,OR,1710,6.0,0,817,1920,1917.0,-3.0,0,8.50,0.00,0.0,76.5,5.14,0.00,0.0,74.0
2,4,2019-08-01,AS,BUR,CA,SEA,WA,1925,-2.0,0,937,2205,2208.0,3.0,1,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0
3,4,2019-08-01,AS,BUR,CA,SEA,WA,800,-7.0,0,937,1040,1042.0,2.0,1,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0
4,4,2019-08-01,AS,BUR,CA,SEA,WA,1050,-1.0,0,937,1330,1321.0,-9.0,0,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28284,1,2019-11-18,B6,BUR,CA,JFK,NY,2107,-9.0,0,2465,521,515.0,-6.0,0,6.71,0.00,0.0,72.5,11.41,0.46,0.0,40.0
28285,1,2019-11-18,B6,BUR,CA,JFK,NY,1445,7.0,0,2465,2300,2325.0,25.0,1,6.71,0.00,0.0,72.5,11.41,0.46,0.0,40.0
28286,2,2019-11-19,B6,BUR,CA,JFK,NY,2107,-11.0,0,2465,521,458.0,-23.0,0,6.93,0.00,0.0,67.5,8.28,0.17,0.0,44.0
28287,5,2019-11-29,B6,BUR,CA,JFK,NY,1435,13.0,0,2465,2250,2226.0,-24.0,0,8.28,0.00,0.0,48.0,16.55,0.00,0.0,37.0
28288,6,2019-11-30,B6,BUR,CA,JFK,NY,2107,1.0,0,2465,521,458.0,-23.0,0,6.04,0.06,0.0,46.0,10.96,0.00,0.0,36.0

In [41]:
# ensure there are no NaN values in the burbank dataframe

burbank2019_df.isna().sum()

DayOfWeek            0
FlightDate           0
Reporting_Airline    0
Origin               0
OriginState          0
Dest                 0
DestState            0
CRSDepTime           0
DepDelay             0
Cancelled            0
Distance             0
CRSArrTime           0
ArrTime              0
ArrDelay             0
Delayed              0
Origin_WIND          0
Origin_PRCP          0
Origin_SNOW          0
Origin_TEMP          0
Dest_WIND            0
Dest_PRCP            0
Dest_SNOW            0
Dest_TEMP            0
dtype: int64

In [42]:
# set the Date to be a datecolumn and extract each of day, month and year separately, create own column for each
# drop the orignal Date column and check that the new columns are correct

burbank2019_df['Day'] = pd.DatetimeIndex(burbank2019_df['FlightDate']).day
burbank2019_df['Month'] = pd.DatetimeIndex(burbank2019_df['FlightDate']).month
burbank2019_df['Year'] = pd.DatetimeIndex(burbank2019_df['FlightDate']).year
burbank2019_df.drop(['FlightDate'], axis=1, inplace=True)
burbank2019_df

,DayOfWeek,Reporting_Airline,Origin,OriginState,Dest,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP,Dest_WIND,Dest_PRCP,Dest_SNOW,Dest_TEMP,Day,Month,Year
0,4,AS,BUR,CA,SEA,WA,1405,6.0,0,937,1645,1641.0,-4.0,0,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,2019
1,4,AS,BUR,CA,PDX,OR,1710,6.0,0,817,1920,1917.0,-3.0,0,8.50,0.00,0.0,76.5,5.14,0.00,0.0,74.0,1,8,2019
2,4,AS,BUR,CA,SEA,WA,1925,-2.0,0,937,2205,2208.0,3.0,1,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,2019
3,4,AS,BUR,CA,SEA,WA,800,-7.0,0,937,1040,1042.0,2.0,1,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,2019
4,4,AS,BUR,CA,SEA,WA,1050,-1.0,0,937,1330,1321.0,-9.0,0,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28284,1,B6,BUR,CA,JFK,NY,2107,-9.0,0,2465,521,515.0,-6.0,0,6.71,0.00,0.0,72.5,11.41,0.46,0.0,40.0,18,11,2019
28285,1,B6,BUR,CA,JFK,NY,1445,7.0,0,2465,2300,2325.0,25.0,1,6.71,0.00,0.0,72.5,11.41,0.46,0.0,40.0,18,11,2019
28286,2,B6,BUR,CA,JFK,NY,2107,-11.0,0,2465,521,458.0,-23.0,0,6.93,0.00,0.0,67.5,8.28,0.17,0.0,44.0,19,11,2019
28287,5,B6,BUR,CA,JFK,NY,1435,13.0,0,2465,2250,2226.0,-24.0,0,8.28,0.00,0.0,48.0,16.55,0.00,0.0,37.0,29,11,2019
28288,6,B6,BUR,CA,JFK,NY,2107,1.0,0,2465,521,458.0,-23.0,0,6.04,0.06,0.0,46.0,10.96,0.00,0.0,36.0,30,11,2019

In [43]:
# create dummy variables for the airlines

airline_df = pd.get_dummies(burbank2019_df['Reporting_Airline'], drop_first=True)
airline_df

       B6  OO  UA  WN
0       0   0   0   0
1       0   0   0   0
2       0   0   0   0
3       0   0   0   0
4       0   0   0   0
...    ..  ..  ..  ..
28284   1   0   0   0
28285   1   0   0   0
28286   1   0   0   0
28287   1   0   0   0
28288   1   0   0   0

[28289 rows x 4 columns]

In [44]:
# create dummy variables for the destination airports

dest_df = pd.get_dummies(burbank2019_df['Dest'], drop_first=True)
dest_df = dest_df.add_prefix('da_')
dest_df

,da_DEN,da_JFK,da_LAS,da_OAK,da_PDX,da_PHX,da_SEA,da_SFO,da_SJC,da_SLC,da_SMF
0,0,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
28284,0,1,0,0,0,0,0,0,0,0,0
28285,0,1,0,0,0,0,0,0,0,0,0
28286,0,1,0,0,0,0,0,0,0,0,0
28287,0,1,0,0,0,0,0,0,0,0,0
28288,0,1,0,0,0,0,0,0,0,0,0

In [45]:
# combine the dummy variables and the original dataframe

burbank2019_df = pd.concat([burbank2019_df, airline_df, dest_df], axis=1) 
burbank2019_df.drop(['Reporting_Airline', 'Dest'], inplace=True, axis=1)
burbank2019_df

,DayOfWeek,Origin,OriginState,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Delayed,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP,Dest_WIND,Dest_PRCP,Dest_SNOW,Dest_TEMP,Day,Month,Year,B6,OO,UA,WN,da_DEN,da_JFK,da_LAS,da_OAK,da_PDX,da_PHX,da_SEA,da_SFO,da_SJC,da_SLC,da_SMF
0,4,BUR,CA,WA,1405,6.0,0,937,1645,1641.0,-4.0,0,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,2019,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,4,BUR,CA,OR,1710,6.0,0,817,1920,1917.0,-3.0,0,8.50,0.00,0.0,76.5,5.14,0.00,0.0,74.0,1,8,2019,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2,4,BUR,CA,WA,1925,-2.0,0,937,2205,2208.0,3.0,1,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,2019,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,4,BUR,CA,WA,800,-7.0,0,937,1040,1042.0,2.0,1,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,2019,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,4,BUR,CA,WA,1050,-1.0,0,937,1330,1321.0,-9.0,0,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,2019,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28284,1,BUR,CA,NY,2107,-9.0,0,2465,521,515.0,-6.0,0,6.71,0.00,0.0,72.5,11.41,0.46,0.0,40.0,18,11,2019,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
28285,1,BUR,CA,NY,1445,7.0,0,2465,2300,2325.0,25.0,1,6.71,0.00,0.0,72.5,11.41,0.46,0.0,40.0,18,11,2019,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
28286,2,BUR,CA,NY,2107,-11.0,0,2465,521,458.0,-23.0,0,6.93,0.00,0.0,67.5,8.28,0.17,0.0,44.0,19,11,2019,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
28287,5,BUR,CA,NY,1435,13.0,0,2465,2250,2226.0,-24.0,0,8.28,0.00,0.0,48.0,16.55,0.00,0.0,37.0,29,11,2019,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
28288,6,BUR,CA,NY,2107,1.0,0,2465,521,458.0,-23.0,0,6.04,0.06,0.0,46.0,10.96,0.00,0.0,36.0,30,11,2019,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0

In [46]:
# move the delayed (target) column to the end

delay_df = burbank2019_df.pop('Delayed')
burbank2019_df['Delayed'] = delay_df
burbank2019_df

,DayOfWeek,Origin,OriginState,DestState,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,ArrTime,ArrDelay,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP,Dest_WIND,Dest_PRCP,Dest_SNOW,Dest_TEMP,Day,Month,Year,B6,OO,UA,WN,da_DEN,da_JFK,da_LAS,da_OAK,da_PDX,da_PHX,da_SEA,da_SFO,da_SJC,da_SLC,da_SMF,Delayed
0,4,BUR,CA,WA,1405,6.0,0,937,1645,1641.0,-4.0,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,2019,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
1,4,BUR,CA,OR,1710,6.0,0,817,1920,1917.0,-3.0,8.50,0.00,0.0,76.5,5.14,0.00,0.0,74.0,1,8,2019,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
2,4,BUR,CA,WA,1925,-2.0,0,937,2205,2208.0,3.0,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,2019,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
3,4,BUR,CA,WA,800,-7.0,0,937,1040,1042.0,2.0,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,2019,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
4,4,BUR,CA,WA,1050,-1.0,0,937,1330,1321.0,-9.0,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,2019,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28284,1,BUR,CA,NY,2107,-9.0,0,2465,521,515.0,-6.0,6.71,0.00,0.0,72.5,11.41,0.46,0.0,40.0,18,11,2019,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
28285,1,BUR,CA,NY,1445,7.0,0,2465,2300,2325.0,25.0,6.71,0.00,0.0,72.5,11.41,0.46,0.0,40.0,18,11,2019,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
28286,2,BUR,CA,NY,2107,-11.0,0,2465,521,458.0,-23.0,6.93,0.00,0.0,67.5,8.28,0.17,0.0,44.0,19,11,2019,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
28287,5,BUR,CA,NY,1435,13.0,0,2465,2250,2226.0,-24.0,8.28,0.00,0.0,48.0,16.55,0.00,0.0,37.0,29,11,2019,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
28288,6,BUR,CA,NY,2107,1.0,0,2465,521,458.0,-23.0,6.04,0.06,0.0,46.0,10.96,0.00,0.0,36.0,30,11,2019,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [47]:
# look at the proportion of delayed flights

burbank2019_df['Delayed'].value_counts()

0    19317
1     8972
Name: Delayed, dtype: int64

In [48]:
# check that all values are numerical (float or int)

burbank2019_df.dtypes

DayOfWeek        int64
Origin          object
OriginState     object
DestState       object
CRSDepTime       int64
DepDelay       float64
Cancelled        int64
Distance         int64
CRSArrTime       int64
ArrTime        float64
ArrDelay       float64
Origin_WIND    float64
Origin_PRCP    float64
Origin_SNOW    float64
Origin_TEMP    float64
Dest_WIND      float64
Dest_PRCP      float64
Dest_SNOW      float64
Dest_TEMP      float64
Day              int64
Month            int64
Year             int64
B6               uint8
OO               uint8
UA               uint8
WN               uint8
da_DEN           uint8
da_JFK           uint8
da_LAS           uint8
da_OAK           uint8
da_PDX           uint8
da_PHX           uint8
da_SEA           uint8
da_SFO           uint8
da_SJC           uint8
da_SLC           uint8
da_SMF           uint8
Delayed          int64
dtype: object

In [49]:
# drop the Year. Origin and OriginState columns because they only have one value each
# drop information about actual arrival times (gives away too much information)

burbank2019_df.drop(columns=['Year',
                             'Origin',
                             'OriginState',
                            #'DepDelay',
                             'ArrTime',
                             'ArrDelay',
                             'DestState'], axis=1, inplace=True)
burbank2019_df

,DayOfWeek,CRSDepTime,DepDelay,Cancelled,Distance,CRSArrTime,Origin_WIND,Origin_PRCP,Origin_SNOW,Origin_TEMP,Dest_WIND,Dest_PRCP,Dest_SNOW,Dest_TEMP,Day,Month,B6,OO,UA,WN,da_DEN,da_JFK,da_LAS,da_OAK,da_PDX,da_PHX,da_SEA,da_SFO,da_SJC,da_SLC,da_SMF,Delayed
0,4,1405,6.0,0,937,1645,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
1,4,1710,6.0,0,817,1920,8.50,0.00,0.0,76.5,5.14,0.00,0.0,74.0,1,8,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
2,4,1925,-2.0,0,937,2205,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
3,4,800,-7.0,0,937,1040,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
4,4,1050,-1.0,0,937,1330,8.50,0.00,0.0,76.5,7.83,0.00,0.0,71.0,1,8,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28284,1,2107,-9.0,0,2465,521,6.71,0.00,0.0,72.5,11.41,0.46,0.0,40.0,18,11,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
28285,1,1445,7.0,0,2465,2300,6.71,0.00,0.0,72.5,11.41,0.46,0.0,40.0,18,11,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
28286,2,2107,-11.0,0,2465,521,6.93,0.00,0.0,67.5,8.28,0.17,0.0,44.0,19,11,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
28287,5,1435,13.0,0,2465,2250,8.28,0.00,0.0,48.0,16.55,0.00,0.0,37.0,29,11,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
28288,6,2107,1.0,0,2465,521,6.04,0.06,0.0,46.0,10.96,0.00,0.0,36.0,30,11,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [50]:
# ensure all values are numerical

burbank2019_df.dtypes

DayOfWeek        int64
CRSDepTime       int64
DepDelay       float64
Cancelled        int64
Distance         int64
CRSArrTime       int64
Origin_WIND    float64
Origin_PRCP    float64
Origin_SNOW    float64
Origin_TEMP    float64
Dest_WIND      float64
Dest_PRCP      float64
Dest_SNOW      float64
Dest_TEMP      float64
Day              int64
Month            int64
B6               uint8
OO               uint8
UA               uint8
WN               uint8
da_DEN           uint8
da_JFK           uint8
da_LAS           uint8
da_OAK           uint8
da_PDX           uint8
da_PHX           uint8
da_SEA           uint8
da_SFO           uint8
da_SJC           uint8
da_SLC           uint8
da_SMF           uint8
Delayed          int64
dtype: object

In [51]:
burbank2019_df.to_csv('burbank2019.csv')